/** Build 1019 controlled Quote Draft execution tests. */
function quoteWorkflowFixture_(changes){changes=changes||{};var locked=false,rows=[],permission=true,relationship=true,auditFailure=false,writeFailure=false,authority={confirmation:{receiptId:'WFR-AAAAAAAAAAAAAAAAAAAAAAAA',correlationId:'a'.repeat(64),eventTimestamp:'2026-08-10T10:00:00.000Z',actor:'user@example.com',actionId:'initiate-quote',destinationModule:'quotes',state:'CONFIRMED',companyId:'COM-1',personId:'PER-1',policyIds:[],draftFingerprint:'b'.repeat(64),contextFingerprint:'c'.repeat(64),expiry:'2026-08-10T10:30:00.000Z'},handoff:{state:'HANDED_OFF'},started:null,committed:null,expired:false},lock={waitLock:function(){if(locked)throw new Error('overlap');locked=true;},hasLock:function(){return locked;},releaseLock:function(){locked=false;}},audit={getExecutionAuthorityLocked:function(){if(!locked)throw new Error('authority outside lock');if(changes.lifecycleError)throw new Error('bad lifecycle');return authority;},appendExecutionStartedLocked:function(a,f){if(!locked)throw new Error('start outside lock');authority.started={state:'EXECUTION_STARTED',metadata:{payloadFingerprint:f}};return{created:true,entry:authority.started};},appendDestinationCommittedLocked:function(a,f,id){if(!locked)throw new Error('commit outside lock');if(auditFailure)throw new Error('audit failed');authority.committed={state:'DESTINATION_COMMITTED',metadata:{payloadFingerprint:f,destinationRecordId:id}};return{created:true,entry:authority.committed};}},quotes={findAllByWorkflowReceiptId:function(){if(!locked)throw new Error('lookup outside lock');return rows.slice();},createWorkflowDraftUnderLock:function(data,actor,receipt,held){if(!locked||held!==lock)throw new Error('create outside lock');if(writeFailure)throw new Error('write failed');var row=Object.assign({},data,{quoteId:'QTE-ABCDEF12',quoteNumber:'QTE-ABCDEF12',workflowReceiptId:receipt,recordVersion:1,isDeleted:false});rows.push(row);return row;}},access={requireModuleOperation:function(){if(!permission)throw new Error('denied');}},service;
  if(changes.authority)Object.keys(changes.authority).forEach(function(k){authority.confirmation[k]=changes.authority[k];});if(changes.policyIds)authority.confirmation.policyIds=changes.policyIds;if(changes.expired)authority.expired=true;if(changes.rows)rows=changes.rows;if(changes.auditFailure)auditFailure=true;if(changes.writeFailure)writeFailure=true;if(changes.permission===false)permission=false;if(changes.relationship===false)relationship=false;
  service=JSKOS.QuoteWorkflowExecution.create({auditRepository:audit,quoteRepository:quotes,accessControl:access,actorProvider:function(){return changes.actor===undefined?'user@example.com':changes.actor;},relationshipValidator:function(){return relationship;},lockProvider:function(){return lock;},clock:function(){return new Date('2026-08-10T10:05:00.000Z');},hash:function(){return'd'.repeat(64);}});return{service:service,authority:authority,rows:function(){return rows;},setAuditFailure:function(v){auditFailure=v;},setWriteFailure:function(v){writeFailure=v;},lock:function(){return locked;}};}
function quoteWorkflowDraft_(){return{insurerName:'Safe Insurer',productName:'Draft Product',expiryDate:'2026-09-10',assignedOwner:'Owner',coverage:'Review required',notes:'Draft only'};}
function quoteWorkflowRejects_(callback,label){try{callback();throw new Error(label);}catch(error){if(error.message===label)throw error;}return{success:true};}
function testBuild1019ValidExecution(){var f=quoteWorkflowFixture_(),x=f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());if(x.state!=='COMPLETED'||x.quote.status!=='Draft'||x.quote.clientDecision!=='Pending'||f.rows().length!==1||f.lock())throw new Error('Valid controlled execution failed.');return{success:true};}
function testBuild1019PreviewNoMutation(){var f=quoteWorkflowFixture_(),x=f.service.preview('WFR-AAAAAAAAAAAAAAAAAAAAAAAA');if(x.state!=='READY_TO_EXECUTE'||f.rows().length||f.authority.started)throw new Error('Preview performed a mutation.');return{success:true};}
function testBuild1019ActorActionDestination(){[['actor','other@example.com'],['actionId','open-policy'],['destinationModule','policies']].forEach(function(item){var options={};if(item[0]==='actor')options.actor=item[1];else{options.authority={};options.authority[item[0]]=item[1];}quoteWorkflowRejects_(function(){quoteWorkflowFixture_(options).service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());},'Invalid '+item[0]+' accepted.');});return{success:true};}
function testBuild1019PermissionAndRelationship(){[{permission:false},{relationship:false}].forEach(function(options){quoteWorkflowRejects_(function(){quoteWorkflowFixture_(options).service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());},'Invalid authority accepted.');});return{success:true};}
function testBuild1019ExpiryAndLifecycle(){[{expired:true},{lifecycleError:true}].forEach(function(options){quoteWorkflowRejects_(function(){quoteWorkflowFixture_(options).service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());},'Invalid lifecycle accepted.');});return{success:true};}
function testBuild1019PolicyBounds(){[['POL-1'],[]].forEach(function(ids){var x=quoteWorkflowFixture_({policyIds:ids}).service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());if(x.state!=='COMPLETED')throw new Error('Valid policy context rejected.');});[['POL-1','POL-2'],['bad id'],['pol-1'],[2],[null]].forEach(function(ids){quoteWorkflowRejects_(function(){quoteWorkflowFixture_({policyIds:ids}).service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());},'Invalid policy context accepted.');});return{success:true};}
function testBuild1019MassAssignment(){['status','clientDecision','actor','companyId','personId','policyId','quoteId','workflowReceiptId','createdAt','recordVersion','unknown'].forEach(function(field){var draft=quoteWorkflowDraft_();draft[field]='INJECTED';quoteWorkflowRejects_(function(){quoteWorkflowFixture_().service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',draft);},'Mass assignment accepted: '+field);});return{success:true};}
function testBuild1019MalformedPayload(){[null,[],{insurerName:''},{insurerName:123},{insurerName:'x',expiryDate:'tomorrow'}].forEach(function(draft){quoteWorkflowRejects_(function(){quoteWorkflowFixture_().service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',draft);},'Malformed payload accepted.');});return{success:true};}
function testBuild1019IdempotentRetry(){var f=quoteWorkflowFixture_(),a=f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_()),b=f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());if(a.state!=='COMPLETED'||b.state!=='ALREADY_COMPLETED'||f.rows().length!==1)throw new Error('Retry created duplicate Quote.');return{success:true};}
function testBuild1019ChangedRetryPayload(){var f=quoteWorkflowFixture_();f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());var changed=quoteWorkflowDraft_();changed.insurerName='Different';quoteWorkflowRejects_(function(){f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',changed);},'Changed retry payload accepted.');if(f.rows().length!==1)throw new Error('Changed retry created a Quote.');return{success:true};}
function testBuild1019DuplicateDestination(){var row=Object.assign(quoteWorkflowDraft_(),{quoteId:'QTE-ABCDEF12',quoteNumber:'QTE-ABCDEF12',workflowReceiptId:'WFR-AAAAAAAAAAAAAAAAAAAAAAAA',status:'Draft',clientDecision:'Pending',companyId:'COM-1',personId:'PER-1',policyId:''});quoteWorkflowRejects_(function(){quoteWorkflowFixture_({rows:[row,Object.assign({},row,{quoteId:'QTE-ABCDEF13'})]}).service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());},'Duplicate destination evidence accepted.');return{success:true};}
function testBuild1019AuditRecovery(){var f=quoteWorkflowFixture_({auditFailure:true}),a=f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());if(a.state!=='COMPLETED_AUDIT_PENDING'||f.rows().length!==1)throw new Error('Post-write audit failure not isolated.');f.setAuditFailure(false);var b=f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());if(b.state!=='COMPLETED'||f.rows().length!==1||!f.authority.committed)throw new Error('Audit reconciliation failed.');return{success:true};}
function testBuild1019WriteFailureRetry(){var f=quoteWorkflowFixture_({writeFailure:true});quoteWorkflowRejects_(function(){f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());},'Quote write failure accepted.');if(f.rows().length||!f.authority.started)throw new Error('Write failure state invalid.');f.setWriteFailure(false);if(f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_()).state!=='COMPLETED'||f.rows().length!==1)throw new Error('Safe write retry failed.');return{success:true};}
function testBuild1019LockCoverage(){var f=quoteWorkflowFixture_();f.service.execute('WFR-AAAAAAAAAAAAAAAAAAAAAAAA',quoteWorkflowDraft_());if(f.lock())throw new Error('Execution lock leaked.');return{success:true};}
function testBuild1019Client360Isolation(){var source=String(apiWorkflowConfirmationHandoff);if(source.indexOf('QuoteRepository')!==-1||source.indexOf('apiQuoteWorkflowExecute')!==-1)throw new Error('Client 360 acquired Quote CRUD ownership.');return{success:true};}
function testBuild1019SchemaContract(){if(JSK_QUOTE_SCHEMA.VERSION!==2||JSK_QUOTE_SCHEMA.HEADERS.filter(function(x){return x==='Workflow Receipt ID';}).length!==1||typeof QuoteRepository.prototype.findAllByWorkflowReceiptId!=='function'||typeof QuoteRepository.prototype.createWorkflowDraftUnderLock!=='function')throw new Error('Additive Quote workflow schema is incomplete.');var createSource=String(QuoteRepository.prototype.create),updateSource=String(QuoteRepository.prototype.update);if(createSource.indexOf('delete x.workflowReceiptId')<0||updateSource.indexOf('delete p.workflowReceiptId')<0)throw new Error('Normal Quote CRUD can control workflow receipt identity.');return{success:true};}
function testBuild1019AuditLifecycleContract(){var source=String(WorkflowAuditRepository.prototype.appendUnlocked_),generic=Object.create(WorkflowAuditRepository.prototype);if(source.indexOf('EXECUTION_STARTED')<0||source.indexOf('DESTINATION_COMMITTED')<0||String(WorkflowAuditRepository.prototype.getExecutionAuthorityLocked).indexOf('assertAuthorityLock_')<0)throw new Error('Execution audit lifecycle is incomplete.');quoteWorkflowRejects_(function(){generic.append({state:'EXECUTED'});},'Generic audit authority accepted.');return{success:true};}
