/** JSK OS Build 1019 - controlled Quote Draft execution. */
var JSKOS=JSKOS||{};
JSKOS.QuoteWorkflowExecution=Object.freeze((function(){'use strict';
  var ACTION='initiate-quote',DESTINATION='quotes',FIELDS=Object.freeze(['insurerName','productName','expiryDate','assignedOwner','coverage','notes']);
  function text_(value,max){if(typeof value!=='string')throw new Error('Quote Draft fields must be text.');var out=value.trim();if(out.length>(max||500))throw new Error('Quote Draft field is too long.');return out;}
  function payload_(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Quote Draft payload is invalid.');var keys=Object.keys(raw);if(keys.some(function(key){return FIELDS.indexOf(key)<0;}))throw new Error('Quote Draft contains unsupported fields.');var out={};FIELDS.forEach(function(key){if(raw[key]!==undefined)out[key]=text_(raw[key],key==='coverage'||key==='notes'?2000:200);});if(!out.insurerName)throw new Error('Insurer Name is required.');if(out.expiryDate&&!/^\d{4}-\d{2}-\d{2}$/.test(out.expiryDate))throw new Error('Expiry Date is invalid.');return out;}
  function hashDefault_(value){var bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8);return bytes.map(function(b){return('0'+((b+256)%256).toString(16)).slice(-2);}).join('');}
  function safeQuote_(quote){return{quoteId:quote.quoteId,quoteNumber:quote.quoteNumber,status:quote.status,clientDecision:quote.clientDecision,companyId:quote.companyId||'',personId:quote.personId||'',policyId:quote.policyId||'',workflowReceiptId:quote.workflowReceiptId};}
  function service(options){options=options||{};var audit=options.auditRepository,quotes=options.quoteRepository,access=options.accessControl,actorProvider=options.actorProvider,relationship=options.relationshipValidator,lockProvider=options.lockProvider,clock=options.clock||function(){return new Date();},hash=options.hash||hashDefault_;if(!audit||!quotes||!access||!actorProvider||!relationship||!lockProvider)throw new Error('Quote workflow execution dependencies are unavailable.');
    function actor_(){var actor=String(actorProvider()||'').trim().toLowerCase();if(!/^[a-z0-9._%+\-]+@[a-z0-9.-]+\.[a-z]{2,}$/.test(actor))throw new Error('Authenticated actor is unavailable.');return actor;}
    function authorize_(authority,actor){access.requireModuleOperation('client360','view');access.requireModuleOperation('quotes','create');var confirmation=authority.confirmation;if(confirmation.actor!==actor||confirmation.actionId!==ACTION||confirmation.destinationModule!==DESTINATION)throw new Error('Workflow execution authority is unavailable.');if(!Array.isArray(confirmation.policyIds)||confirmation.policyIds.length>1)throw new Error('Workflow policy context is unavailable.');if(confirmation.policyIds.some(function(id){return typeof id!=='string'||!/^[A-Z0-9][A-Z0-9._:-]{0,99}$/.test(id);}))throw new Error('Workflow policy context is unavailable.');if(!relationship({companyId:confirmation.companyId,personId:confirmation.personId,policyIds:confirmation.policyIds.slice()}))throw new Error('Workflow relationship is unavailable.');return confirmation;}
    function quoteData_(confirmation,draft){return Object.assign({},draft,{companyId:confirmation.companyId,personId:confirmation.personId,policyId:confirmation.policyIds[0]||'',status:'Draft',clientDecision:'Pending'});}
    function same_(quote,data,receiptId){return Boolean(quote&&!quote.isDeleted&&quote.workflowReceiptId===receiptId&&quote.status==='Draft'&&quote.clientDecision==='Pending'&&String(quote.companyId||'')===data.companyId&&String(quote.personId||'')===data.personId&&String(quote.policyId||'')===data.policyId&&FIELDS.every(function(key){return String(quote[key]||'')===String(data[key]||'');}));}
    function locked_(receiptId,draft,execute){var lock=lockProvider();lock.waitLock(30000);try{var now=clock(),authority=audit.getExecutionAuthorityLocked(receiptId,now,lock),actor=actor_(),confirmation=authorize_(authority,actor),normalized=draft?payload_(draft):null,data=normalized?quoteData_(confirmation,normalized):null,fingerprint=normalized?hash(JSKOS.WorkflowConfirmation.canonicalize(data)):null,matches=quotes.findAllByWorkflowReceiptId(receiptId);if(matches.length>1)throw new Error('Ambiguous destination receipt evidence.');if(!matches.length&&(authority.expired||authority.committed))throw new Error(authority.expired?'Workflow receipt expired.':'Destination commit evidence has no Quote.');if(matches.length&&(!authority.started||authority.committed&&authority.committed.metadata.destinationRecordId!==matches[0].quoteId))throw new Error('Destination receipt lifecycle is unavailable.');if(!execute)return{state:matches.length?'ALREADY_COMPLETED':'READY_TO_EXECUTE',receiptId:receiptId,context:{companyId:confirmation.companyId,personId:confirmation.personId,policyIds:confirmation.policyIds.slice()},quote:matches.length?safeQuote_(matches[0]):null};if(matches.length){if(!same_(matches[0],data,receiptId))throw new Error('Destination receipt evidence does not match this request.');var wasCommitted=Boolean(authority.committed);try{audit.appendDestinationCommittedLocked(authority,fingerprint,matches[0].quoteId,now,lock);return{state:wasCommitted?'ALREADY_COMPLETED':'COMPLETED',quote:safeQuote_(matches[0])};}catch(error){return{state:'COMPLETED_AUDIT_PENDING',quote:safeQuote_(matches[0])};}}
        audit.appendExecutionStartedLocked(authority,fingerprint,now,lock);var created=quotes.createWorkflowDraftUnderLock(data,actor,receiptId,lock),verified=quotes.findAllByWorkflowReceiptId(receiptId);if(verified.length!==1||!same_(verified[0],data,receiptId)||verified[0].quoteId!==created.quoteId)throw new Error('Quote Draft verification failed.');try{audit.appendDestinationCommittedLocked(authority,fingerprint,verified[0].quoteId,clock(),lock);}catch(error){return{state:'COMPLETED_AUDIT_PENDING',quote:safeQuote_(verified[0])};}return{state:'COMPLETED',quote:safeQuote_(verified[0])};
      }finally{if(typeof lock.hasLock!=='function'||lock.hasLock())lock.releaseLock();}}
    return{preview:function(receiptId){return locked_(String(receiptId||''),null,false);},execute:function(receiptId,draft){return locked_(String(receiptId||''),draft,true);}};
  }
  return{create:service,ACTION:ACTION,DESTINATION:DESTINATION,ALLOWED_FIELDS:FIELDS};
})());

function quoteWorkflowRelationship_(context){var company=context.companyId?new CompanyRepository().findById(context.companyId):null,person=context.personId?new PeopleRepository().findById(context.personId):null,policy=context.policyIds.length?new PolicyRepository().findById(context.policyIds[0]):null;if(context.companyId&&!company)return false;if(context.personId&&!person)return false;if(company&&person&&String(person.companyId||'').trim().toUpperCase()!==context.companyId)return false;if(policy&&((context.companyId&&String(policy.companyId||'').trim().toUpperCase()!==context.companyId)||(context.personId&&String(policy.personId||'').trim().toUpperCase()!==context.personId)))return false;if(context.policyIds.length&&!policy)return false;return Boolean(context.companyId||context.personId);}
function quoteWorkflowExecutionService_(){return JSKOS.QuoteWorkflowExecution.create({auditRepository:new WorkflowAuditRepository(),quoteRepository:new QuoteRepository(),accessControl:JSKOS.AccessControl,actorProvider:function(){return JSKOS.ConfigService.getCurrentUser();},relationshipValidator:quoteWorkflowRelationship_,lockProvider:function(){return LockService.getScriptLock();}});}
function quoteWorkflowApi_(callback){try{return{success:true,data:JSON.parse(JSON.stringify(callback())),error:null,meta:{build:1019,version:'1.5.7',destination:'quotes'}};}catch(error){return{success:false,data:null,error:{code:'QUOTE_WORKFLOW_UNAVAILABLE',message:'Controlled Quote Draft execution is unavailable.'},meta:{build:1019,version:'1.5.7',destination:'quotes'}};}}
function apiQuoteWorkflowPreview(payload){payload=payload||{};return quoteWorkflowApi_(function(){return quoteWorkflowExecutionService_().preview(payload.receiptId);});}
function apiQuoteWorkflowExecute(payload){payload=payload||{};return quoteWorkflowApi_(function(){return quoteWorkflowExecutionService_().execute(payload.receiptId,payload.draft);});}
