/** JSK OS Build 1020 - Quote execution reconciliation control. */
var JSKOS=JSKOS||{};
JSKOS.QuoteWorkflowReconciliation=Object.freeze((function(){'use strict';
  var ACTION='initiate-quote',DESTINATION='quotes';
  function hashDefault_(value){var bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8);return bytes.map(function(b){return('0'+((b+256)%256).toString(16)).slice(-2);}).join('');}
  function safeResult_(state,reason,receiptId,authority,matchCount,quoteId,identityVerified){var verified=Boolean(authority&&authority.reconciliationAuthorityVerified);return{state:state,reasonCode:reason,receiptId:receiptId,lifecycle:{confirmed:Boolean(authority&&authority.confirmation),handedOff:Boolean(authority&&authority.handoff),executionStarted:Boolean(authority&&authority.started),destinationCommitted:Boolean(authority&&authority.committed),expired:Boolean(authority&&authority.expired)},destination:{matchCount:Math.min(Number(matchCount||0),2),quoteId:quoteId||'',identityVerified:Boolean(identityVerified)},authority:{serverRecomputed:verified,relationshipVerified:verified,fingerprintsVerified:verified}};}
  function service(options){options=options||{};var audit=options.auditRepository,quotes=options.quoteRepository,access=options.accessControl,actorProvider=options.actorProvider,relationship=options.relationshipValidator,prepare=options.prepareIntent,lockProvider=options.lockProvider,clock=options.clock||function(){return new Date();},hash=options.hash||hashDefault_,diagnostic=options.diagnostic||function(){};if(!audit||!quotes||!access||!actorProvider||!relationship||!prepare||!lockProvider)throw new Error('Quote workflow reconciliation dependencies are unavailable.');
    function actor_(){var actor=String(actorProvider()||'').trim().toLowerCase();if(!/^[a-z0-9._%+\-]+@[a-z0-9.-]+\.[a-z]{2,}$/.test(actor))throw new Error('Authenticated actor is unavailable.');return actor;}
    function authorize_(authority,actor){access.requireModuleOperation('client360','view');access.requireModuleOperation('quotes','view');access.requireModuleOperation('quotes','reconcile');var confirmation=authority.confirmation;if(confirmation.actor!==actor||confirmation.actionId!==ACTION||confirmation.destinationModule!==DESTINATION)throw new Error('Workflow reconciliation authority is unavailable.');if(!Array.isArray(confirmation.policyIds)||confirmation.policyIds.length>1||confirmation.policyIds.some(function(id){return typeof id!=='string'||!/^[A-Z0-9][A-Z0-9._:-]{0,99}$/.test(id);}))throw new Error('Workflow policy context is unavailable.');var context={companyId:confirmation.companyId,personId:confirmation.personId,policyIds:confirmation.policyIds.slice()};if(!relationship(context))throw new Error('Workflow relationship is unavailable.');var intent=prepare(ACTION,context);if(!intent||intent.status!=='READY'||intent.actionId!==ACTION||intent.destinationModule!==DESTINATION)throw new Error('Workflow intent is unavailable.');var normalized=intent.context||{},policies=Array.isArray(normalized.policyIds)?normalized.policyIds:[];if(normalized.companyId!==context.companyId||normalized.personId!==context.personId||policies.join('\u0000')!==context.policyIds.join('\u0000'))throw new Error('Workflow context is unavailable.');var contextFingerprint=hash(JSKOS.WorkflowConfirmation.canonicalize(context)),draftFingerprint=hash(JSKOS.WorkflowConfirmation.canonicalize(intent.draftPayload||{})),correlationId=hash(JSKOS.WorkflowConfirmation.canonicalize({actor:actor,actionId:intent.actionId,destinationModule:intent.destinationModule,context:contextFingerprint,draft:draftFingerprint}));if(confirmation.contextFingerprint!==contextFingerprint||confirmation.draftFingerprint!==draftFingerprint||confirmation.correlationId!==correlationId)throw new Error('Workflow authority fingerprints are unavailable.');return context;}
    function immutableIdentity_(quote,confirmation,receiptId){return Boolean(quote&&/^QTE-[A-F0-9]{8}$/.test(String(quote.quoteId||''))&&quote.workflowReceiptId===receiptId&&String(quote.companyId||'')===confirmation.companyId&&String(quote.personId||'')===confirmation.personId&&String(quote.policyId||'')===(confirmation.policyIds[0]||''));}
    function report_(result){try{diagnostic(result.state,{reasonCode:result.reasonCode,receiptId:result.receiptId,lifecycle:result.lifecycle,destination:{matchCount:result.destination.matchCount,quoteId:result.destination.identityVerified?result.destination.quoteId:'',identityVerified:result.destination.identityVerified}});}catch(error){}return result;}
    function classifyLocked_(receiptId,actor,lock){var authority;try{authority=audit.getExecutionAuthorityLocked(receiptId,clock(),lock);}catch(error){if(error&&error.code==='WORKFLOW_AUDIT_LOOKUP_FAILURE')return{result:safeResult_('UNCERTAIN','AUDIT_LOOKUP_UNAVAILABLE',receiptId,null,0,'',false)};return{result:safeResult_('CONFLICT','INTEGRITY_REJECTED',receiptId,null,0,'',false)};}try{authorize_(authority,actor);authority.reconciliationAuthorityVerified=true;}catch(error){return{result:safeResult_('CONFLICT','INTEGRITY_REJECTED',receiptId,authority,0,'',false)};}var matches;try{matches=quotes.findWorkflowReceiptMatchesForReconciliation(receiptId);}catch(error){return{result:safeResult_('UNCERTAIN','DESTINATION_LOOKUP_UNAVAILABLE',receiptId,authority,0,'',false),authority:authority};}if(matches.length>1)return{result:safeResult_('CONFLICT','MULTIPLE_DESTINATION_MATCHES',receiptId,authority,matches.length,'',false),authority:authority};if(!matches.length){if(authority.committed)return{result:safeResult_('CONFLICT','COMMIT_WITHOUT_DESTINATION',receiptId,authority,0,'',false),authority:authority};if(authority.started)return{result:safeResult_('UNCERTAIN','EXECUTION_OUTCOME_UNRESOLVED',receiptId,authority,0,'',false),authority:authority};return{result:safeResult_(authority.expired?'EXPIRED':'UNCERTAIN',authority.expired?'RECEIPT_EXPIRED':'NO_DESTINATION_EVIDENCE',receiptId,authority,0,'',false),authority:authority};}var quote=matches[0],identity=immutableIdentity_(quote,authority.confirmation,receiptId);if(!identity)return{result:safeResult_('CONFLICT','DESTINATION_IDENTITY_MISMATCH',receiptId,authority,1,'',false),authority:authority};if(!authority.started)return{result:safeResult_('CONFLICT','DESTINATION_WITHOUT_EXECUTION_START',receiptId,authority,1,quote.quoteId,true),authority:authority,quote:quote};if(authority.committed){if(authority.committed.metadata.destinationRecordId!==quote.quoteId||authority.committed.metadata.payloadFingerprint!==authority.started.metadata.payloadFingerprint)return{result:safeResult_('CONFLICT','COMMIT_EVIDENCE_MISMATCH',receiptId,authority,1,'',false),authority:authority,quote:quote};return{result:safeResult_('VERIFIED','DESTINATION_COMMITTED',receiptId,authority,1,quote.quoteId,true),authority:authority,quote:quote};}return{result:safeResult_('RECONCILIATION_REQUIRED','VERIFIED_DESTINATION_AUDIT_PENDING',receiptId,authority,1,quote.quoteId,true),authority:authority,quote:quote};}
    function operate_(receiptId,reconcile){receiptId=String(receiptId||'');if(!/^WFR-[A-F0-9]{24}$/.test(receiptId))throw new Error('Workflow receipt is invalid.');var actor=actor_();access.requireModuleOperation('client360','view');access.requireModuleOperation('quotes','view');access.requireModuleOperation('quotes','reconcile');var lock=lockProvider();lock.waitLock(30000);try{var classified=classifyLocked_(receiptId,actor,lock),result=classified.result;if(!reconcile||result.state!=='RECONCILIATION_REQUIRED')return report_(result);try{audit.appendDestinationCommittedLocked(classified.authority,classified.authority.started.metadata.payloadFingerprint,classified.quote.quoteId,clock(),lock);return report_(safeResult_('VERIFIED','RECONCILIATION_COMPLETED',receiptId,Object.assign({},classified.authority,{committed:true}),1,classified.quote.quoteId,true));}catch(error){if(error&&error.code==='WORKFLOW_AUDIT_STORAGE_FAILURE')return report_(safeResult_('AUDIT_PENDING','AUDIT_STORAGE_UNAVAILABLE',receiptId,classified.authority,1,classified.quote.quoteId,true));return report_(safeResult_('CONFLICT','INTEGRITY_REJECTED',receiptId,classified.authority,1,'',false));}}finally{if(typeof lock.hasLock!=='function'||lock.hasLock())lock.releaseLock();}}
    return{inspect:function(receiptId){return operate_(receiptId,false);},reconcile:function(receiptId){return operate_(receiptId,true);}};
  }
  return{create:service,ACTION:ACTION,DESTINATION:DESTINATION};
})());

function quoteWorkflowReconciliationLogger_(){return typeof JSKLoggerFactory!=='undefined'?JSKLoggerFactory.createConsoleLogger('QuoteWorkflowReconciliation'):null;}
function quoteWorkflowReconciliationService_(){var logger=quoteWorkflowReconciliationLogger_();return JSKOS.QuoteWorkflowReconciliation.create({auditRepository:new WorkflowAuditRepository(),quoteRepository:new QuoteRepository(),accessControl:JSKOS.AccessControl,actorProvider:function(){return JSKOS.ConfigService.getCurrentUser();},relationshipValidator:quoteWorkflowRelationship_,prepareIntent:function(actionId,context){return JSKOS.WorkflowIntent.prepare(actionId,context,workflowIntentOptions_());},lockProvider:function(){return LockService.getScriptLock();},diagnostic:function(state,context){if(!logger)return;var level=state==='CONFLICT'?'warn':'info';logger[level]('Quote workflow reconciliation '+state,context);}});}
function quoteWorkflowReconciliationPayload_(payload){if(!payload||typeof payload!=='object'||Array.isArray(payload)||Object.keys(payload).some(function(key){return key!=='receiptId';}))throw new Error('Reconciliation request is invalid.');return String(payload.receiptId||'');}
function quoteWorkflowReconciliationApi_(callback){try{return{success:true,data:JSON.parse(JSON.stringify(callback())),error:null,meta:{build:1020,version:'1.5.8',businessMutation:false,auditOnly:true}};}catch(error){return{success:false,data:null,error:{code:'QUOTE_RECONCILIATION_UNAVAILABLE',message:'Quote workflow reconciliation is unavailable.'},meta:{build:1020,version:'1.5.8',businessMutation:false,auditOnly:true}};}}
function apiQuoteWorkflowReconciliationInspect(payload){return quoteWorkflowReconciliationApi_(function(){return quoteWorkflowReconciliationService_().inspect(quoteWorkflowReconciliationPayload_(payload));});}
function apiQuoteWorkflowReconcile(payload){return quoteWorkflowReconciliationApi_(function(){return quoteWorkflowReconciliationService_().reconcile(quoteWorkflowReconciliationPayload_(payload));});}
