/** JSK OS Build 1021 - bounded, advisory Quote reconciliation operations queue. */
var JSKOS=JSKOS||{};
JSKOS.QuoteReconciliationQueue=Object.freeze((function(){'use strict';
  function unavailable_(){return{items:[],sourceState:'UNAVAILABLE',scanLimit:JSK_WORKFLOW_AUDIT.MAX_AUDIT_ROWS_SCANNED,rowsScanned:0,returned:0,truncated:false,nextCursor:null,advisory:true,authoritative:false};}
  function safe_(result){result=result||unavailable_();return{items:(result.items||[]).map(function(item){return{receiptId:item.receiptId,executionStartedAt:item.executionStartedAt,expired:Boolean(item.expired),actionId:'initiate-quote',destinationModule:'quotes',advisoryState:'NEEDS_INSPECTION'};}),sourceState:['READY','EMPTY','PARTIAL'].indexOf(result.sourceState)>=0?result.sourceState:'UNAVAILABLE',scanLimit:JSK_WORKFLOW_AUDIT.MAX_AUDIT_ROWS_SCANNED,rowsScanned:Math.min(Math.max(Number(result.rowsScanned)||0,0),JSK_WORKFLOW_AUDIT.MAX_AUDIT_ROWS_SCANNED),returned:Math.min(Math.max(Number(result.returned)||0,0),JSK_WORKFLOW_AUDIT.MAX_CANDIDATE_RECEIPTS),truncated:Boolean(result.truncated),nextCursor:result.nextCursor===null?null:Number(result.nextCursor),advisory:true,authoritative:false};}
  function create(options){options=options||{};var audit=options.auditRepository,access=options.accessControl,actorProvider=options.actorProvider,clock=options.clock||function(){return new Date();};if(!audit||!access||!actorProvider)throw new Error('Quote reconciliation queue dependencies are unavailable.');return{list:function(request){var actor=String(actorProvider()||'').trim().toLowerCase();if(!/^[a-z0-9._%+\-]+@[a-z0-9.-]+\.[a-z]{2,}$/.test(actor))throw new Error('Authenticated actor is unavailable.');access.requireModuleOperation('client360','view');access.requireModuleOperation('quotes','view');access.requireModuleOperation('quotes','reconcile');try{return safe_(audit.listQuoteExecutionQueueBounded({cursor:request.cursor,limit:request.limit,now:clock()}));}catch(error){if(error&&error.code==='WORKFLOW_AUDIT_LOOKUP_FAILURE')return unavailable_();throw error;}}};}
  return{create:create};
})());

function quoteReconciliationQueuePayload_(payload){if(payload===undefined||payload===null)payload={};if(typeof payload!=='object'||Array.isArray(payload))throw new Error('Reconciliation queue request is invalid.');var keys=Object.keys(payload),allowed={cursor:true,limit:true};if(keys.some(function(key){return!allowed[key];}))throw new Error('Reconciliation queue request is invalid.');function bounded_(value,name,maximum,optional){if(value===undefined&&optional)return undefined;if(typeof value!=='number'||!isFinite(value)||Math.floor(value)!==value||value<1||value>maximum)throw new Error('Reconciliation queue '+name+' is invalid.');return value;}return{cursor:bounded_(payload.cursor,'cursor',Number.MAX_SAFE_INTEGER,true),limit:bounded_(payload.limit,'limit',JSK_WORKFLOW_AUDIT.MAX_CANDIDATE_RECEIPTS,true)};}
function quoteReconciliationQueueService_(){var spreadsheet=JSKOS.ConfigService.getSpreadsheet();return JSKOS.QuoteReconciliationQueue.create({auditRepository:new WorkflowAuditRepository(spreadsheet,{readOnly:true}),accessControl:JSKOS.AccessControl,actorProvider:function(){return JSKOS.ConfigService.getCurrentUser();}});}
function apiQuoteReconciliationQueueList(payload){try{return{success:true,data:JSON.parse(JSON.stringify(quoteReconciliationQueueService_().list(quoteReconciliationQueuePayload_(payload)))),error:null,meta:{build:1021,version:'1.5.9',advisory:true,authoritative:false,businessMutation:false}};}catch(error){return{success:false,data:null,error:{code:'QUOTE_RECONCILIATION_QUEUE_UNAVAILABLE',message:'Quote reconciliation operations are unavailable.'},meta:{build:1021,version:'1.5.9',advisory:true,authoritative:false,businessMutation:false}};}}
