/** GARUDA visiting-card transient validation and deterministic merge boundary. */
var JSKOS = JSKOS || {};
JSKOS.GarudaVisitingCard = (function () {
  'use strict';
  var MAX_BYTES = 5 * 1024 * 1024;
  var MIME = Object.freeze(['image/jpeg', 'image/png', 'image/webp']);
  var FIELDS = Object.freeze(['personName', 'designation', 'primaryMobile', 'mobile', 'alternateMobile', 'email', 'companyName', 'website', 'companyPhone', 'address', 'location', 'tagline', 'productsServices', 'gstin', 'cin', 'linkedIn']);
  function error_(code, message) { var error = new Error(message); error.code = code; error.status = 400; return error; }
  function clean_(value) { return String(value || '').replace(/[\u0000-\u001F]/g, '').trim().substring(0, 2000); }
  function validateImage(side, required) { if (!side || !side.base64) { if (required) throw error_('GARUDA_CARD_IMAGE_REQUIRED', 'Add a Front visiting-card photo before extraction.'); return null; } var mimeType = clean_(side.mimeType).toLowerCase(), base64 = String(side.base64 || '').trim().replace(/^data:[^;]+;base64,/, ''); if (base64.length > Math.ceil(MAX_BYTES * 4 / 3) + 4 || MIME.indexOf(mimeType) === -1 || !/^[A-Za-z0-9+/]+={0,2}$/.test(base64)) throw error_('GARUDA_CARD_IMAGE_INVALID', 'Use a valid JPG, PNG or WEBP visiting-card image.'); var bytes = Math.floor(base64.length * 3 / 4) - ((base64.match(/=+$/) || [''])[0].length); if (!bytes || bytes > MAX_BYTES) throw error_('GARUDA_CARD_IMAGE_INVALID', 'Each visiting-card image must be 5 MB or less.'); return { mimeType: mimeType, base64: base64, bytes: bytes }; }
  function normalizeWebsite_(value) { var text = clean_(value); if (!text) return ''; if (!/^https?:\/\//i.test(text)) text = 'https://' + text; if (!/^https?:\/\/(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z][a-z0-9-]*(?:[\/?#][^\s]*)?$/i.test(text)) return ''; return text; }
  function values_(record, field) { var value = record && record[field], list = Array.isArray(value) ? value : [value]; return list.map(clean_).filter(Boolean); }
  function sanitizeSide_(side) { var out = {}; FIELDS.forEach(function (field) { var values = values_(side, field); if (values.length) out[field] = values; }); return out; }
  function merge(front, back) { front = front || {}; back = back || {}; var fields = {}, conflicts = [], provenance = {}, confidence = {}; FIELDS.forEach(function (field) { var f = values_(front, field), b = values_(back, field), all = [], seen = {}; f.concat(b).forEach(function (value) { var normalized = field === 'website' ? normalizeWebsite_(value) : value; var key = normalized.toLowerCase(); if (normalized && !seen[key]) { seen[key] = true; all.push(normalized); } }); if (!all.length) return; fields[field] = all[0]; if ((field === 'primaryMobile' || field === 'mobile') && all.length > 1 && !fields.alternateMobile) fields.alternateMobile = all[1]; if (all.length > 1 && field !== 'primaryMobile' && field !== 'mobile') conflicts.push({ field: field, values: all, status: 'REQUIRES_REVIEW' }); provenance[field] = f.length && b.length ? 'VISITING_CARD_FRONT_AND_BACK' : f.length ? 'VISITING_CARD_FRONT' : 'VISITING_CARD_BACK'; var scores = []; if (front.confidence && typeof front.confidence[field] === 'number') scores.push(front.confidence[field]); if (back.confidence && typeof back.confidence[field] === 'number') scores.push(back.confidence[field]); confidence[field] = scores.length ? Math.min.apply(Math, scores) : null; }); return { fields: fields, conflicts: conflicts, requiresReview: true, provenance: provenance, confidence: confidence, front: sanitizeSide_(front), back: sanitizeSide_(back) }; }
  return Object.freeze({ validateImage: validateImage, merge: merge, supportedMimeTypes: MIME, maxBytes: MAX_BYTES });
})();
