/** GARUDA read-only CRM entity resolution. Never creates or mutates records. */
var JSKOS = JSKOS || {};
JSKOS.GarudaCrmResolver = (function () {
  'use strict';
  function text_(value) { return String(value == null ? '' : value).trim(); }
  function words_(value) { return text_(value).toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim(); }
  function email_(value) { return text_(value).toLowerCase(); }
  function phone_(value) { var digits = text_(value).replace(/\D/g, ''); if (digits.length === 12 && digits.indexOf('91') === 0) digits = digits.substring(2); if (digits.length === 11 && digits.charAt(0) === '0') digits = digits.substring(1); return digits; }
  function domain_(value) { var host = text_(value).toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '').split(/[\/?#]/)[0].replace(/:\d+$/, ''); return /^(?:[a-z0-9-]+\.)+[a-z0-9-]+$/.test(host) ? host : ''; }
  function companyName_(value) { return words_(value).replace(/\bprivate limited\b/g, ' pvt ltd ').replace(/\bpvt limited\b/g, ' pvt ltd ').replace(/\bpvt ltd\b/g, ' pvt ltd ').replace(/\blimited\b/g, ' ltd ').replace(/\s+/g, ' ').trim(); }
  function location_(value) { return words_(value); }
  function containsLocation_(record, expected) { expected = location_(expected); if (!expected) return false; var actual = location_([record.area, record.zone, record.city, record.state, record.address].filter(Boolean).join(' ')); return Boolean(actual && (actual.indexOf(expected) !== -1 || expected.indexOf(actual) !== -1 || expected.split(' ').some(function (part) { return part.length >= 4 && actual.split(' ').indexOf(part) !== -1; }))); }
  function similarity_(left, right) { left = companyName_(left); right = companyName_(right); if (!left || !right) return 0; var previous = [], current = [], i, j; for (j = 0; j <= right.length; j++) previous[j] = j; for (i = 1; i <= left.length; i++) { current = [i]; for (j = 1; j <= right.length; j++) current[j] = Math.min(current[j - 1] + 1, previous[j] + 1, previous[j - 1] + (left.charAt(i - 1) === right.charAt(j - 1) ? 0 : 1)); previous = current; } return 1 - previous[right.length] / Math.max(left.length, right.length); }
  function candidate_(type, record, reason, score) { return { id: text_(record[type === 'person' ? 'personId' : 'companyId']), label: text_(type === 'person' ? record.fullName : record.companyName), reason: reason, confidence: score }; }
  function result_(type, ranked) { var seen = {}, unique = ranked.filter(function (item) { if (!item.id || seen[item.id]) return false; seen[item.id] = true; return true; }).sort(function (a, b) { return b.priority - a.priority || b.confidence - a.confidence || a.id.localeCompare(b.id); }); if (!unique.length) return { status: 'NO_MATCH', id: '', message: 'No existing CRM match', candidates: [] }; var top = unique[0], peers = unique.filter(function (item) { return item.priority === top.priority; }); var strong = top.priority >= 300 || (top.priority === 200 && top.confidence >= 0.92 && (!unique[1] || top.confidence - unique[1].confidence >= 0.08)); if (strong && peers.length === 1) return { status: 'RESOLVED', id: top.id, message: 'Resolved existing record', candidates: [top] }; return { status: 'POSSIBLE_MATCHES', id: '', message: 'Possible match — review', candidates: unique.slice(0, 8) }; }
  function company_(input, companies) { var ranked = [], wantedDomain = domain_(input.website), wantedName = companyName_(input.companyName), wantedLocation = input.location; (companies || []).forEach(function (record) { var id = text_(record.companyId); if (!id) return; var recordDomain = domain_(record.website), recordName = companyName_(record.companyName), exactName = Boolean(wantedName && wantedName === recordName); if (wantedDomain && wantedDomain === recordDomain) ranked.push(Object.assign(candidate_('company', record, 'EXACT_DOMAIN', 1), { priority: 400 })); else if (exactName) ranked.push(Object.assign(candidate_('company', record, 'EXACT_COMPANY_NAME', containsLocation_(record, wantedLocation) ? 1 : 0.96), { priority: 350 })); else if (wantedName && containsLocation_(record, wantedLocation) && similarity_(wantedName, recordName) >= 0.88) ranked.push(Object.assign(candidate_('company', record, 'COMPANY_NAME_LOCATION', 0.93), { priority: 300 })); else { var fuzzy = similarity_(wantedName, recordName); if (wantedName.length >= 6 && fuzzy >= 0.92) ranked.push(Object.assign(candidate_('company', record, 'HIGH_CONFIDENCE_COMPANY_NAME', fuzzy), { priority: 200 })); } }); return result_('company', ranked); }
  function person_(input, people, companies, companyResolution) { var ranked = [], wantedEmail = email_(input.email), wantedPhone = phone_(input.primaryMobile || input.mobile), wantedName = words_(input.personName), wantedCompany = companyName_(input.companyName), wantedLocation = input.location, companyById = {}; (companies || []).forEach(function (record) { companyById[text_(record.companyId)] = record; }); (people || []).forEach(function (record) { var id = text_(record.personId), recordCompany = companyById[text_(record.companyId)] || {}, sameName = Boolean(wantedName && wantedName === words_(record.fullName)), sameCompany = Boolean(wantedCompany && wantedCompany === companyName_(recordCompany.companyName)), resolvedCompany = Boolean(companyResolution.status === 'RESOLVED' && text_(record.companyId) === companyResolution.id); if (!id) return; if (wantedEmail && wantedEmail === email_(record.email)) ranked.push(Object.assign(candidate_('person', record, 'EXACT_EMAIL', 1), { priority: 500 })); else if (wantedPhone && wantedPhone.length >= 10 && wantedPhone === phone_(record.mobile || record.whatsApp)) ranked.push(Object.assign(candidate_('person', record, 'EXACT_MOBILE', 0.99), { priority: 450 })); else if (sameName && (sameCompany || resolvedCompany)) ranked.push(Object.assign(candidate_('person', record, 'EXACT_NAME_COMPANY', containsLocation_(recordCompany, wantedLocation) ? 0.96 : 0.92), { priority: 350 })); else if (sameName && sameCompany && containsLocation_(recordCompany, wantedLocation)) ranked.push(Object.assign(candidate_('person', record, 'NAME_COMPANY_LOCATION', 0.94), { priority: 300 })); else if (sameName) ranked.push(Object.assign(candidate_('person', record, 'NAME_ONLY_AMBIGUOUS', 0.65), { priority: 100 })); }); return result_('person', ranked); }
  function resolve(input, people, companies) { input = input || {}; var companyResolution = company_(input, companies); return { company: companyResolution, person: person_(input, people, companies, companyResolution), readOnly: true }; }
  return Object.freeze({ resolve: resolve, normalizeEmail: email_, normalizePhone: phone_, normalizeDomain: domain_, normalizeName: words_, normalizeCompanyName: companyName_ });
})();
