/** GARUDA visiting-card transient validation and deterministic merge boundary. */
var JSKOS = JSKOS || {};
JSKOS.GarudaVisitingCard = (function () {
  'use strict';
  var MAX_BYTES = 5 * 1024 * 1024;
  var MIME = Object.freeze(['image/jpeg', 'image/png', 'image/webp']);
  var FIELDS = Object.freeze(['personName', 'designation', 'primaryMobile', 'mobile', 'alternateMobile', 'email', 'companyName', 'website', 'companyPhone', 'address', 'location', 'tagline', 'productsServices', 'gstin', 'cin', 'linkedIn']);
  function error_(code, message) { var error = new Error(message); error.code = code; error.status = 400; return error; }
  function clean_(value) { return String(value || '').replace(/[\u0000-\u001F]/g, '').trim().substring(0, 2000); }
  function validateImage(side, required) { if (!side || !side.base64) { if (required) throw error_('GARUDA_CARD_IMAGE_REQUIRED', 'Add a Front visiting-card photo before extraction.'); return null; } var mimeType = clean_(side.mimeType).toLowerCase(), base64 = String(side.base64 || '').trim().replace(/^data:[^;]+;base64,/, ''); if (base64.length > Math.ceil(MAX_BYTES * 4 / 3) + 4 || MIME.indexOf(mimeType) === -1 || !/^[A-Za-z0-9+/]+={0,2}$/.test(base64)) throw error_('GARUDA_CARD_IMAGE_INVALID', 'Use a valid JPG, PNG or WEBP visiting-card image.'); var bytes = Math.floor(base64.length * 3 / 4) - ((base64.match(/=+$/) || [''])[0].length); if (!bytes || bytes > MAX_BYTES) throw error_('GARUDA_CARD_IMAGE_INVALID', 'Each visiting-card image must be 5 MB or less.'); return { mimeType: mimeType, base64: base64, bytes: bytes }; }
  function normalizeWebsite_(value) { var text = clean_(value); if (!text) return ''; if (!/^https?:\/\//i.test(text)) text = 'https://' + text; if (!/^https?:\/\/(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z][a-z0-9-]*(?:[\/?#][^\s]*)?$/i.test(text)) return ''; return text; }
  function values_(record, field) { var value = record && record[field], list = Array.isArray(value) ? value : [value]; return list.map(clean_).filter(Boolean); }
  function sanitizeSide_(side) { var out = {}; FIELDS.forEach(function (field) { var values = values_(side, field); if (values.length) out[field] = values; }); return out; }
  function sourceText_(value) { return String(value || '').replace(/\r/g, '').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, '').trim().substring(0, 12000); }
  function analysisAutofill_(fields, front, back) { var out = { companyId: '', personId: '' }, allowed = ['companyName', 'personName', 'designation', 'website', 'location', 'productsServices']; allowed.forEach(function (field) { out[field] = clean_(fields[field]); }); var parts = [], frontText = sourceText_(front && front.sourceText), backText = sourceText_(back && back.sourceText); if (frontText) parts.push('FRONT:\n' + frontText); if (backText) parts.push('BACK:\n' + backText); out.extractedText = parts.join('\n\n').substring(0, 24000); return out; }
  function heading_(value) { return /^(?:risk management|wealth creation|business protection|trust\s*(?:&|and)\s*support|our services|corporate insurance|products?(?:\s*\/\s*services?)?|services|about us|contact us)$/i.test(clean_(value)); }
  function incompleteCompany_(value) { return /^(?:investment|services|solutions|enterprises|industries)$/i.test(clean_(value)); }
  function validName_(value) { value = clean_(value); return /^(?:[A-Z][A-Za-z.'-]+\s+){1,3}[A-Z][A-Za-z.'-]+$/.test(value) && !heading_(value) && !/^(?:RISK|WEALTH|BUSINESS|TRUST|OUR)\b/.test(value) && !/\b(?:solutions?|services?|management|protection|creation)\b/i.test(value); }
  function validCompany_(value) { value = clean_(value); return Boolean(value && !heading_(value) && !/\b(?:solutions?\s+for|services?\s+for|we\s+(?:provide|offer)|your\s+(?:business|family|future))\b/i.test(value) && !/\b(?:for|providing|protecting|creating|supporting)\b/i.test(value) && value.split(/\s+/).length <= 7); }
  function validDesignation_(value) { value = clean_(value); return Boolean(value && value.length <= 80 && !heading_(value) && !/[.!?]$/.test(value) && !/\b(?:solutions?\s+for|services?\s+for)\b/i.test(value)); }
  function completeAddress_(value) { value = clean_(value); return Boolean(value && (/\b\d{6}\b/.test(value) || ((value.match(/,/g) || []).length >= 2 && /\b(?:road|rd\.?|street|building|nagar|city|district|state|india)\b/i.test(value)))); }
  function review_(list, field, values, reason) { if (!list.some(function (item) { return item.field === field && item.reason === reason; })) list.push({ field: field, values: (values || []).slice(), status: 'REQUIRES_REVIEW', reason: reason }); }
  function merge(front, back) { front = front || {}; back = back || {}; var fields = {}, conflicts = [], provenance = {}, confidence = {}, identity = { personName: validName_, companyName: validCompany_, designation: validDesignation_ }; FIELDS.forEach(function (field) { var rawFront = values_(front, field), rawBack = values_(back, field), validator = identity[field], f = validator ? rawFront.filter(validator) : rawFront, b = validator ? rawBack.filter(validator) : rawBack, all = [], seen = {}; if (validator) { rawFront.filter(function (value) { return !validator(value); }).concat(rawBack.filter(function (value) { return !validator(value); })).forEach(function (value) { review_(conflicts, field, [value], heading_(value) ? 'PROBABLE_HEADING' : 'SEMANTICALLY_INVALID'); }); } if (field === 'companyName') { var incomplete = f.filter(incompleteCompany_).concat(b.filter(incompleteCompany_)); if (incomplete.length) { review_(conflicts, field, incomplete, 'INCOMPLETE_COMPANY_NAME'); f = f.filter(function (value) { return !incompleteCompany_(value); }); b = b.filter(function (value) { return !incompleteCompany_(value); }); } } f.concat(b).forEach(function (value) { var normalized = field === 'website' ? normalizeWebsite_(value) : value; var key = normalized.toLowerCase(); if (normalized && !seen[key]) { seen[key] = true; all.push(normalized); } }); if (!all.length) return; var frontScore = front.confidence && front.confidence[field], backScore = back.confidence && back.confidence[field], backOnlyIdentity = Boolean(validator && !f.length && b.length); if (backOnlyIdentity && (typeof backScore !== 'number' || backScore < 0.85)) { review_(conflicts, field, b, 'LOW_CONFIDENCE_BACK_IDENTITY'); return; } fields[field] = all[0]; if ((field === 'primaryMobile' || field === 'mobile') && all.length > 1 && !fields.alternateMobile) fields.alternateMobile = all[1]; if (all.length > 1 && field !== 'primaryMobile' && field !== 'mobile') review_(conflicts, field, all, 'FRONT_BACK_CONFLICT'); provenance[field] = f.length && b.length ? 'VISITING_CARD_FRONT_AND_BACK' : f.length ? 'VISITING_CARD_FRONT' : 'VISITING_CARD_BACK'; var scores = []; if (typeof frontScore === 'number') scores.push(frontScore); if (typeof backScore === 'number') scores.push(backScore); confidence[field] = scores.length ? Math.min.apply(Math, scores) : null; if (validator && confidence[field] !== null && confidence[field] < 0.7) review_(conflicts, field, all, 'LOW_CONFIDENCE_IDENTITY'); if (field === 'address' && !completeAddress_(fields[field])) review_(conflicts, field, all, 'INCOMPLETE_ADDRESS'); }); ['personName', 'companyName'].forEach(function (field) { if (!fields[field]) review_(conflicts, field, [], 'REQUIRED_IDENTITY_MISSING'); }); return { fields: fields, analysisAutofill: analysisAutofill_(fields, front, back), conflicts: conflicts, requiresReview: true, provenance: provenance, confidence: confidence, front: sanitizeSide_(front), back: sanitizeSide_(back) }; }
  return Object.freeze({ validateImage: validateImage, merge: merge, supportedMimeTypes: MIME, maxBytes: MAX_BYTES });
})();
