/** JSK OS Build 1006 - Communication outbox repository. */

class CommunicationRepository {
  constructor(spreadsheet) { this.spreadsheet=spreadsheet||JSKOS.ConfigService.getSpreadsheet(); this.sheet=this.spreadsheet.getSheetByName(JSK_COMMUNICATION_SCHEMA.SHEET_NAME); if(!this.sheet)throw new Error('Communication_Outbox not found.'); this.headers=this.sheet.getRange(1,1,1,this.sheet.getLastColumn()).getDisplayValues()[0].map(function(v){return String(v||'').trim();}); this.map={}; this.headers.forEach(function(h,i){if(h)this.map[h]=i;},this); }
  queue(data,actor) {
    var item=this._normalize(data); this._validate(item); var key=String(item['Idempotency Key']||'').trim();
    if(key){var existing=this.findByIdempotencyKey(key);if(existing)return existing;}
    var now=new Date(),record=this._empty(); Object.assign(record,item,{
      'Communication ID':'COM-'+Utilities.formatDate(now,'Asia/Kolkata','yyyyMMddHHmmss')+'-'+Utilities.getUuid().replace(/-/g,'').substring(0,6).toUpperCase(),
      'Direction':item['Direction']||'Outbound','Status':item['Status']||'Queued','Provider':item['Provider']||'Pending Configuration','Attempt Count':0,
      'Scheduled At':item['Scheduled At']||now,'Created At':now,'Created By':this._actor(actor),'Updated At':now,'Updated By':this._actor(actor),'Record Version':1,'Is Deleted':false
    }); this.sheet.appendRow(this._toRow(record)); return this.findById(record['Communication ID'],true);
  }
  findById(id,includeDeleted){var entry=this._find(function(record){return String(record['Communication ID']).toUpperCase()===String(id||'').trim().toUpperCase();});if(!entry||(!includeDeleted&&this._bool(entry.record['Is Deleted'])))return null;return this._format(entry.record);}
  findByIdempotencyKey(key){var entry=this._find(function(record){return !this._bool(record['Is Deleted'])&&String(record['Idempotency Key'])===key;}.bind(this));return entry?this._format(entry.record):null;}
  update(id,changes,actor,expectedVersion){var lock=LockService.getDocumentLock()||LockService.getScriptLock();lock.waitLock(30000);try{var entry=this._find(function(record){return String(record['Communication ID']).toUpperCase()===String(id||'').trim().toUpperCase();});if(!entry)throw new Error('Communication not found.');var version=Number(entry.record['Record Version'])||1;if(expectedVersion!==undefined&&Number(expectedVersion)!==version){var conflict=new Error('Communication was modified by another process.');conflict.code='VERSION_CONFLICT';conflict.currentVersion=version;throw conflict;}var updated=Object.assign({},entry.record,this._normalize(changes));this._validate(updated);updated['Updated At']=new Date();updated['Updated By']=this._actor(actor);updated['Record Version']=version+1;this.sheet.getRange(entry.row,1,1,this.headers.length).setValues([this._toRow(updated)]);SpreadsheetApp.flush();return this._format(updated);}finally{lock.releaseLock();}}
  search(criteria){criteria=criteria||{};var channel=String(criteria.channel||'').toLowerCase(),status=String(criteria.status||'').toLowerCase(),query=String(criteria.query||'').toLowerCase();var items=this._entries().filter(function(entry){var r=entry.record;if(!r['Communication ID']||this._bool(r['Is Deleted']))return false;if(channel&&String(r['Channel']).toLowerCase()!==channel)return false;if(status&&String(r['Status']).toLowerCase()!==status)return false;if(query&&['Recipient','Recipient Name','Subject','Message','Policy ID'].every(function(h){return String(r[h]||'').toLowerCase().indexOf(query)===-1;}))return false;return true;},this).map(function(entry){return this._format(entry.record);},this);items.sort(function(a,b){return String(b.createdAt||'').localeCompare(String(a.createdAt||''));});return{items:items,totalItems:items.length};}
  _entries(){var count=this.sheet.getLastRow()-1;if(count<1)return[];return this.sheet.getRange(2,1,count,this.headers.length).getValues().map(function(row,index){var record={};this.headers.forEach(function(h,i){if(h)record[h]=row[i];});return{row:index+2,record:record};},this);}
  _find(predicate){return this._entries().filter(function(entry){return predicate(entry.record);})[0]||null;}
  _empty(){var r={};this.headers.forEach(function(h){if(h)r[h]='';});return r;}_toRow(r){return this.headers.map(function(h){return r[h]===undefined||r[h]===null?'':r[h];});}_bool(v){return v===true||String(v).toLowerCase()==='true';}_actor(v){return String(v||'').trim()||Session.getActiveUser().getEmail()||'SYSTEM';}
  _normalize(data){data=data||{};var aliases={channel:'Channel',direction:'Direction',templateKey:'Template Key',recipient:'Recipient',recipientName:'Recipient Name',subject:'Subject',message:'Message',status:'Status',provider:'Provider',providerMessageId:'Provider Message ID',idempotencyKey:'Idempotency Key',scheduledAt:'Scheduled At',sentAt:'Sent At',deliveredAt:'Delivered At',readAt:'Read At',attemptCount:'Attempt Count',nextRetryAt:'Next Retry At',lastError:'Last Error',companyId:'Company ID',personId:'Person ID',policyId:'Policy ID',taskId:'Task ID',meetingId:'Meeting ID',metadataJson:'Metadata JSON'};var out={};Object.keys(data).forEach(function(k){var h=aliases[k]||k;if(this.map[h]===undefined)return;var v=data[k];if(h.indexOf(' At')!==-1&&v)out[h]=new Date(v);else if(h==='Attempt Count')out[h]=Number(v)||0;else out[h]=String(v||'').trim();},this);return out;}
  _validate(item){if(JSK_COMMUNICATION_SCHEMA.CHANNEL_VALUES.indexOf(item['Channel'])===-1)throw new Error('Select a valid communication channel.');if(!String(item['Recipient']||'').trim())throw new Error('Recipient is required.');if(!String(item['Message']||'').trim())throw new Error('Message is required.');if(item['Status']&&JSK_COMMUNICATION_SCHEMA.STATUS_VALUES.indexOf(item['Status'])===-1)throw new Error('Select a valid communication status.');if(item['Channel']==='Email'&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(String(item['Recipient'])))throw new Error('Email recipient is invalid.');if(item['Channel']==='WhatsApp'&&!/^\d{10,15}$/.test(String(item['Recipient']).replace(/\D/g,'')))throw new Error('WhatsApp recipient is invalid.');}
  _format(record){var special={'Communication ID':'communicationId','Provider Message ID':'providerMessageId','Idempotency Key':'idempotencyKey','Company ID':'companyId','Person ID':'personId','Policy ID':'policyId','Task ID':'taskId','Meeting ID':'meetingId','Metadata JSON':'metadataJson'};var out={};this.headers.forEach(function(h){if(!h)return;var k=special[h]||h.replace(/[^a-zA-Z0-9]+(.)/g,function(_,c){return c.toUpperCase();}).replace(/^[A-Z]/,function(c){return c.toLowerCase();});var v=record[h];out[k]=v instanceof Date?Utilities.formatDate(v,'Asia/Kolkata','yyyy-MM-dd HH:mm:ss'):v;});out.recordVersion=Number(record['Record Version'])||1;out.isDeleted=this._bool(record['Is Deleted']);return out;}
}
