/** Build 1018 append-only Workflow_Audit evidence store. */
var JSK_WORKFLOW_AUDIT=Object.freeze({SHEET:'Workflow_Audit',HEADERS:Object.freeze(['Receipt ID','Correlation ID','Event Timestamp','Actor','Action ID','Destination Module','State','Company ID','Person ID','Policy IDs','Draft Fingerprint','Context Fingerprint','Expiry','Parent Receipt ID','Safe Metadata'])});
class WorkflowAuditRepository{
  constructor(spreadsheet){this.spreadsheet=spreadsheet||JSKOS.ConfigService.getSpreadsheet();this.sheet=this.ensure_();}
  ensure_(){var s=this.spreadsheet.getSheetByName(JSK_WORKFLOW_AUDIT.SHEET);if(!s){s=this.spreadsheet.insertSheet(JSK_WORKFLOW_AUDIT.SHEET);s.getRange(1,1,1,JSK_WORKFLOW_AUDIT.HEADERS.length).setValues([JSK_WORKFLOW_AUDIT.HEADERS.slice()]);s.setFrozenRows(1);}return s;}
  append(entry){if(!JSKOS.WorkflowConfirmation.STATES[entry.state])throw new Error('Invalid workflow audit state.');var lock=LockService.getScriptLock();lock.waitLock(30000);try{this.sheet.appendRow([entry.receiptId,entry.correlationId,entry.eventTimestamp,entry.actor,entry.actionId,entry.destinationModule,entry.state,entry.companyId,entry.personId,(entry.policyIds||[]).slice(0,50).join(','),entry.draftFingerprint,entry.contextFingerprint,entry.expiry,entry.parentReceiptId||'',JSON.stringify(entry.metadata||{})]);SpreadsheetApp.flush();}finally{lock.releaseLock();}return entry;}
  rows_(limit){var last=this.sheet.getLastRow();if(last<2)return[];var count=Math.min(Math.max(Number(limit)||100,1),500,last-1),start=last-count+1,values=this.sheet.getRange(start,1,count,JSK_WORKFLOW_AUDIT.HEADERS.length).getValues();return values.map(function(r){return{receiptId:String(r[0]),correlationId:String(r[1]),eventTimestamp:String(r[2]),actor:String(r[3]),actionId:String(r[4]),destinationModule:String(r[5]),state:String(r[6]),companyId:String(r[7]),personId:String(r[8]),policyIds:String(r[9]||'').split(',').filter(Boolean).slice(0,50),draftFingerprint:String(r[10]),contextFingerprint:String(r[11]),expiry:String(r[12]),parentReceiptId:String(r[13]),metadata:{}};});}
  findByCorrelation(id,limit){return this.rows_(limit).filter(function(x){return x.correlationId===id&&x.state==='CONFIRMED';});}
  findByReceipt(id,limit){return this.rows_(limit).filter(function(x){return x.receiptId===id;});}
}
