/** Build 1018 append-only Workflow_Audit evidence store. */
var JSK_WORKFLOW_AUDIT=Object.freeze({SHEET:'Workflow_Audit',HEADERS:Object.freeze(['Receipt ID','Correlation ID','Event Timestamp','Actor','Action ID','Destination Module','State','Company ID','Person ID','Policy IDs','Draft Fingerprint','Context Fingerprint','Expiry','Parent Receipt ID','Safe Metadata']),LOOKUP_LIMIT:500,LOCK_TIMEOUT_MS:30000});
class WorkflowAuditRepository{
  constructor(spreadsheet){this.spreadsheet=spreadsheet||JSKOS.ConfigService.getSpreadsheet();this.sheet=this.initialize_();}
  lock_(){return LockService.getScriptLock();}
  withLock_(callback){var lock=this.lock_();lock.waitLock(JSK_WORKFLOW_AUDIT.LOCK_TIMEOUT_MS);try{return callback.call(this);}finally{if(typeof lock.hasLock!=='function'||lock.hasLock())lock.releaseLock();}}
  initialize_(){return this.withLock_(function(){var sheet=this.spreadsheet.getSheetByName(JSK_WORKFLOW_AUDIT.SHEET);if(!sheet){sheet=this.spreadsheet.insertSheet(JSK_WORKFLOW_AUDIT.SHEET);sheet.getRange(1,1,1,JSK_WORKFLOW_AUDIT.HEADERS.length).setValues([JSK_WORKFLOW_AUDIT.HEADERS.slice()]);sheet.setFrozenRows(1);}this.validateSchema_(sheet);return sheet;});}
  validateSchema_(sheet){if(!sheet||sheet.getLastColumn()!==JSK_WORKFLOW_AUDIT.HEADERS.length||sheet.getLastRow()<1)throw new Error('Workflow_Audit schema is incompatible.');var actual=sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0];if(actual.length!==JSK_WORKFLOW_AUDIT.HEADERS.length||actual.some(function(value,index){return String(value)!==JSK_WORKFLOW_AUDIT.HEADERS[index];}))throw new Error('Workflow_Audit schema is incompatible.');return true;}
  row_(entry){return[entry.receiptId,entry.correlationId,entry.eventTimestamp,entry.actor,entry.actionId,entry.destinationModule,entry.state,entry.companyId,entry.personId,(entry.policyIds||[]).slice(0,50).join(','),entry.draftFingerprint,entry.contextFingerprint,entry.expiry,entry.parentReceiptId||'',JSON.stringify(entry.metadata||{})];}
  sameList_(left,right){return(left||[]).join('\u0000')===(right||[]).join('\u0000');}
  validConfirmation_(entry){var eventTime=new Date(entry.eventTimestamp).getTime(),expiry=new Date(entry.expiry).getTime();return Boolean(entry&&entry.state==='CONFIRMED'&&entry.receiptId&&entry.correlationId&&entry.actor&&entry.actionId&&entry.destinationModule&&entry.draftFingerprint&&entry.contextFingerprint&&!entry.parentReceiptId&&!isNaN(eventTime)&&!isNaN(expiry)&&expiry>eventTime&&(entry.policyIds||[]).length<=50);}
  sameConfirmation_(existing,entry){return this.validConfirmation_(existing)&&existing.correlationId===entry.correlationId&&existing.actionId===entry.actionId&&existing.actor===entry.actor&&existing.destinationModule===entry.destinationModule&&existing.companyId===entry.companyId&&existing.personId===entry.personId&&this.sameList_(existing.policyIds,entry.policyIds)&&existing.contextFingerprint===entry.contextFingerprint&&existing.draftFingerprint===entry.draftFingerprint;}
  appendUnlocked_(entry){if(!JSKOS.WorkflowConfirmation.STATES[entry.state])throw new Error('Invalid workflow audit state.');this.validateSchema_(this.sheet);this.sheet.appendRow(this.row_(entry));SpreadsheetApp.flush();return entry;}
  append(entry){return this.withLock_(function(){return this.appendUnlocked_(entry);});}
  rowsUnlocked_(limit){this.validateSchema_(this.sheet);var last=this.sheet.getLastRow();if(last<2)return[];var count=Math.min(Math.max(Number(limit)||100,1),JSK_WORKFLOW_AUDIT.LOOKUP_LIMIT,last-1),start=last-count+1,values=this.sheet.getRange(start,1,count,JSK_WORKFLOW_AUDIT.HEADERS.length).getValues();return values.map(function(r){return{receiptId:String(r[0]),correlationId:String(r[1]),eventTimestamp:String(r[2]),actor:String(r[3]),actionId:String(r[4]),destinationModule:String(r[5]),state:String(r[6]),companyId:String(r[7]),personId:String(r[8]),policyIds:String(r[9]||'').split(',').filter(Boolean).slice(0,50),draftFingerprint:String(r[10]),contextFingerprint:String(r[11]),expiry:String(r[12]),parentReceiptId:String(r[13]),metadata:{}};});}
  findByCorrelation(id,limit){return this.rowsUnlocked_(limit).filter(function(x){return x.correlationId===id&&x.state==='CONFIRMED';});}
  findByReceipt(id,limit){return this.rowsUnlocked_(limit).filter(function(x){return x.receiptId===id;});}
  appendConfirmedUnique(entry){return this.withLock_(function(){if(!this.validConfirmation_(entry))throw new Error('Invalid workflow confirmation evidence.');var eventTime=new Date(entry.eventTimestamp).getTime(),recent=this.rowsUnlocked_(JSK_WORKFLOW_AUDIT.LOOKUP_LIMIT),matches=recent.filter(function(x){return x.correlationId===entry.correlationId&&x.state==='CONFIRMED';});if(matches.some(function(existing){return!this.sameConfirmation_(existing,entry);},this))throw new Error('Contradictory workflow confirmation evidence.');var active=matches.filter(function(existing){return new Date(existing.expiry).getTime()>eventTime;});if(active.length>1)throw new Error('Ambiguous workflow confirmation evidence.');if(active.length===1)return{created:false,entry:active[0]};var total=this.sheet.getLastRow()-1;if(total>recent.length&&recent.length){var oldest=new Date(recent[0].eventTimestamp),windowStart=eventTime-30*60000;if(isNaN(oldest.getTime())||oldest.getTime()>windowStart)throw new Error('Workflow confirmation lookup is incomplete.');}return{created:true,entry:this.appendUnlocked_(entry)};});}
  appendHandoffUnique(receiptId,event,now){return this.withLock_(function(){var history=this.findByReceipt(receiptId,JSK_WORKFLOW_AUDIT.LOOKUP_LIMIT),confirmed=history.filter(function(x){return x.state==='CONFIRMED';}),handed=history.filter(function(x){return x.state==='HANDED_OFF';}),invalid=history.filter(function(x){return['CONFIRMED','HANDED_OFF'].indexOf(x.state)<0;});if(confirmed.length!==1||handed.length>1||invalid.length||!this.validConfirmation_(confirmed[0]))throw new Error('Ambiguous workflow receipt lifecycle.');var parent=confirmed[0];if(handed.length===1){var prior=handed[0],handoffTime=new Date(prior.eventTimestamp).getTime(),consistent=prior.receiptId===parent.receiptId&&prior.correlationId===parent.correlationId&&prior.actor===parent.actor&&prior.actionId===parent.actionId&&prior.destinationModule===parent.destinationModule&&prior.companyId===parent.companyId&&prior.personId===parent.personId&&this.sameList_(prior.policyIds,parent.policyIds)&&prior.draftFingerprint===parent.draftFingerprint&&prior.contextFingerprint===parent.contextFingerprint&&prior.expiry===parent.expiry&&prior.parentReceiptId===parent.receiptId&&!isNaN(handoffTime)&&handoffTime>=new Date(parent.eventTimestamp).getTime()&&handoffTime<=new Date(parent.expiry).getTime();if(!consistent)throw new Error('Contradictory workflow handoff evidence.');return{created:false,entry:prior};}if(new Date(parent.expiry)<now)throw new Error('Workflow receipt expired.');var next=Object.assign({},event,{receiptId:parent.receiptId,correlationId:parent.correlationId,actor:parent.actor,actionId:parent.actionId,destinationModule:parent.destinationModule,companyId:parent.companyId,personId:parent.personId,policyIds:parent.policyIds.slice(0,50),draftFingerprint:parent.draftFingerprint,contextFingerprint:parent.contextFingerprint,expiry:parent.expiry,state:'HANDED_OFF',parentReceiptId:parent.receiptId});return{created:true,entry:this.appendUnlocked_(next)};});}
}
