/** Build 1017 Workflow Intent security contracts. */
function workflowIntentAccess_(denied){return{hasPermission:function(p){return(denied||[]).indexOf(p)<0;}};}
function workflowIntentOptionsTest_(denied,safe){return{accessControl:workflowIntentAccess_(denied),relationshipValidator:function(){return{safe:safe!==false};}};}
function testBuild1017IntentNormalization(){var x=JSKOS.WorkflowIntent.prepare('open-policy',{companyId:' com-1 ',policyIds:['pol-1','POL-1']},workflowIntentOptionsTest_());if(x.context.companyId!=='COM-1'||x.context.policyIds.join(',')!=='POL-1'||x.status!=='READY')throw new Error('Intent normalization failed.');return{success:true};}
function testBuild1017UnsupportedAndMalformed(){var u=JSKOS.WorkflowIntent.prepare('delete-client',{companyId:'COM-1'},workflowIntentOptionsTest_()),m=JSKOS.WorkflowIntent.prepare('open-company',{companyId:'bad id'},workflowIntentOptionsTest_());if(u.status!=='UNSUPPORTED'||m.status!=='BLOCKED'||u.draftPayload.companyId||m.destinationRoute)throw new Error('Unsupported/malformed intent did not fail closed.');return{success:true};}
function testBuild1017PermissionIsolation(){var x=JSKOS.WorkflowIntent.prepare('initiate-quote',{companyId:'COM-SECRET'},workflowIntentOptionsTest_(['quotes.create']));if(x.status!=='BLOCKED'||x.destinationRoute||Object.keys(x.draftPayload).length)throw new Error('Unauthorized intent leaked context.');return{success:true};}
function testBuild1017IncompleteIntent(){var x=JSKOS.WorkflowIntent.prepare('open-policy',{companyId:'COM-1'},workflowIntentOptionsTest_());if(x.status!=='INCOMPLETE'||x.missingFields[0]!=='policyIds')throw new Error('Incomplete intent failed.');return{success:true};}
function testBuild1017AllowlistedDraft(){var x=JSKOS.WorkflowIntent.prepare('open-person',{companyId:'COM-1',personId:'PER-1',policyIds:['POL-1'],secret:'NO'},workflowIntentOptionsTest_());var keys=Object.keys(x.draftPayload).sort().join(',');if(keys!=='actionId,actionType,companyId,destinationModule,personId,policyIds'||JSON.stringify(x).indexOf('NO')>=0)throw new Error('Draft allowlist failed.');return{success:true};}
function testBuild1017BoundsAndRelationship(){var ids=[];for(var i=0;i<80;i++)ids.push('POL-'+i);var b=JSKOS.WorkflowIntent.prepare('open-policy',{companyId:'COM-1',policyIds:ids},workflowIntentOptionsTest_()),r=JSKOS.WorkflowIntent.prepare('open-person',{companyId:'COM-1',personId:'PER-2'},workflowIntentOptionsTest_([],false));if(b.context.policyIds.length!==50||r.status!=='BLOCKED'||r.reasonCode!=='ACTION_NOT_AVAILABLE')throw new Error('Bounds/relationship isolation failed.');return{success:true};}
function testBuild1017HandoffRevalidation(){var calls=0,access={hasPermission:function(){calls++;return calls===1;}};var x=JSKOS.WorkflowIntent.handoff('open-company',{companyId:'COM-1'},{accessControl:access});if(x.status!=='BLOCKED'||x.href||calls<2)throw new Error('Handoff did not revalidate permission.');var ready=JSKOS.WorkflowIntent.handoff('open-company',{companyId:'COM-1'},workflowIntentOptionsTest_());if(ready.status!=='READY'||ready.href.indexOf('?page=companies&clientAction=open-company')!==0)throw new Error('Safe handoff failed.');return{success:true};}
function testBuild1017ReadOnly(){var x=JSKOS.WorkflowIntent.prepare('open-company',{companyId:'COM-1'},workflowIntentOptionsTest_());if(!x.metadata.readOnly||x.metadata.persisted||typeof apiWorkflowIntentExecute==='function')throw new Error('Workflow intent gained persistence/write ownership.');return{success:true};}
function testBuild1017UiRendering(){var content=renderClient360Ui().getContent();['Review Workflow Intent','apiWorkflowIntentPrepare','Continue to destination','prepare-action'].forEach(function(marker){if(content.indexOf(marker)<0)throw new Error('Workflow intent UI marker missing: '+marker);});if(content.indexOf('apiWorkflowIntentHandoff')<0&&content.indexOf('apiWorkflowConfirmationHandoff')<0)throw new Error('Server-authoritative handoff marker missing.');return{success:true};}
