/** Build 1018 Workflow_Audit schema and locking contracts. */
function workflowAuditSheetTest_(headers){return{headers:(headers||[]).slice(),data:[],guard:null,getLastColumn:function(){return this.headers.length;},getLastRow:function(){return(this.headers.length?1:0)+this.data.length;},getRange:function(row,col,count,width){var self=this;return{getDisplayValues:function(){return[self.headers.slice(col-1,col-1+width)];},getValues:function(){if(self.guard&&!self.guard.held)throw new Error('evidence read outside lock');return self.data.slice(row-2,row-2+count).map(function(values){return values.slice(col-1,col-1+width);});},setValues:function(values){self.headers=values[0].slice();}};},setFrozenRows:function(){},appendRow:function(values){if(this.guard&&!this.guard.held)throw new Error('evidence append outside lock');this.data.push(values.slice());}};}
function workflowAuditSpreadsheetTest_(headers){var sheet=headers===null?null:workflowAuditSheetTest_(headers),inserts=0;return{getSheetByName:function(){return sheet;},insertSheet:function(){inserts++;if(sheet)throw new Error('duplicate sheet');sheet=workflowAuditSheetTest_([]);return sheet;},inserts:function(){return inserts;},sheet:function(){return sheet;}};}
function workflowAuditLockTest_(){return{held:false,waits:0,releases:0,waitLock:function(){this.held=true;this.waits++;},hasLock:function(){return this.held;},releaseLock:function(){this.held=false;this.releases++;}};}
function workflowAuditWithLock_(callback){var previous=typeof LockService==='undefined'?undefined:LockService,previousSpreadsheetApp=typeof SpreadsheetApp==='undefined'?undefined:SpreadsheetApp,lock=workflowAuditLockTest_();globalThis.LockService={getScriptLock:function(){return lock;}};globalThis.SpreadsheetApp={flush:function(){}};try{return callback(lock);}finally{if(previous===undefined)delete globalThis.LockService;else globalThis.LockService=previous;if(previousSpreadsheetApp===undefined)delete globalThis.SpreadsheetApp;else globalThis.SpreadsheetApp=previousSpreadsheetApp;}}
function testBuild1018ValidAuditSchema(){return workflowAuditWithLock_(function(lock){var ss=workflowAuditSpreadsheetTest_(JSK_WORKFLOW_AUDIT.HEADERS),repo=new WorkflowAuditRepository(ss);if(!repo.sheet||lock.waits!==1||lock.releases!==1)throw new Error('Valid schema initialization failed.');return{success:true};});}
function testBuild1018InvalidAuditSchemas(){var variants=[JSK_WORKFLOW_AUDIT.HEADERS.slice(0,-1),JSK_WORKFLOW_AUDIT.HEADERS.slice().reverse(),JSK_WORKFLOW_AUDIT.HEADERS.slice().concat(['Extra']),JSK_WORKFLOW_AUDIT.HEADERS.map(function(x,i){return i===1?JSK_WORKFLOW_AUDIT.HEADERS[0]:x;}),JSK_WORKFLOW_AUDIT.HEADERS.map(function(x,i){return i===2?'Renamed':x;})];variants.forEach(function(headers){workflowAuditWithLock_(function(){try{new WorkflowAuditRepository(workflowAuditSpreadsheetTest_(headers));throw new Error('invalid schema accepted');}catch(e){if(e.message==='invalid schema accepted')throw e;}});});return{success:true};}
function testBuild1018FirstInitialization(){return workflowAuditWithLock_(function(lock){var ss=workflowAuditSpreadsheetTest_(null),repo=new WorkflowAuditRepository(ss);if(ss.inserts()!==1||repo.sheet.headers.join('|')!==JSK_WORKFLOW_AUDIT.HEADERS.join('|')||lock.waits!==1||lock.releases!==1)throw new Error('First-time schema initialization failed.');return{success:true};});}
function testBuild1018ConcurrentInitializationContract(){return workflowAuditWithLock_(function(lock){var ss=workflowAuditSpreadsheetTest_(null);new WorkflowAuditRepository(ss);new WorkflowAuditRepository(ss);if(ss.inserts()!==1||lock.waits!==2||lock.releases!==2)throw new Error('Concurrent initialization contract failed.');return{success:true};});}
function workflowAuditEntryTest_(){return{receiptId:'WFR-UNPREDICTABLE-1',correlationId:'CORR-1',eventTimestamp:'2026-08-09T10:00:00.000Z',actor:'user@example.com',actionId:'initiate-quote',destinationModule:'quotes',state:'CONFIRMED',companyId:'COM-1',personId:'',policyIds:[],draftFingerprint:'DRAFT-1',contextFingerprint:'CONTEXT-1',expiry:'2026-08-09T10:30:00.000Z',parentReceiptId:'',metadata:{}};}
function testBuild1018AtomicRepositoryEvidence(){return workflowAuditWithLock_(function(lock){var ss=workflowAuditSpreadsheetTest_(JSK_WORKFLOW_AUDIT.HEADERS),repo=new WorkflowAuditRepository(ss),entry=workflowAuditEntryTest_();repo.sheet.guard=lock;var first=repo.appendConfirmedUnique(entry),again=repo.appendConfirmedUnique(Object.assign({},entry,{receiptId:'WFR-UNPREDICTABLE-2'})),handoff=repo.appendHandoffUnique(entry.receiptId,{eventTimestamp:'2026-08-09T10:01:00.000Z'},new Date('2026-08-09T10:01:00.000Z')),handoffAgain=repo.appendHandoffUnique(entry.receiptId,{eventTimestamp:'2026-08-09T10:02:00.000Z'},new Date('2026-08-09T10:02:00.000Z'));if(!first.created||again.created||!handoff.created||handoffAgain.created||again.entry.receiptId!==entry.receiptId||repo.sheet.data.length!==2)throw new Error('Atomic repository lifecycle failed.');repo.sheet.data[1][10]='TAMPERED';try{repo.appendHandoffUnique(entry.receiptId,{eventTimestamp:'2026-08-09T10:03:00.000Z'},new Date('2026-08-09T10:03:00.000Z'));throw new Error('contradictory evidence accepted');}catch(e){if(e.message==='contradictory evidence accepted')throw e;}return{success:true};});}
function testBuild1018MalformedConfirmationFailsClosed(){return workflowAuditWithLock_(function(lock){var ss=workflowAuditSpreadsheetTest_(JSK_WORKFLOW_AUDIT.HEADERS),repo=new WorkflowAuditRepository(ss),entry=workflowAuditEntryTest_();repo.sheet.guard=lock;repo.appendConfirmedUnique(entry);repo.sheet.data[0][12]='not-a-date';try{repo.appendConfirmedUnique(Object.assign({},entry,{receiptId:'WFR-UNPREDICTABLE-2'}));throw new Error('malformed evidence accepted');}catch(e){if(e.message==='malformed evidence accepted')throw e;}if(repo.sheet.data.length!==1)throw new Error('Malformed evidence caused an append.');return{success:true};});}
function testBuild1018ExpiryWindowAuthority(){return workflowAuditWithLock_(function(lock){var ss=workflowAuditSpreadsheetTest_(JSK_WORKFLOW_AUDIT.HEADERS),repo=new WorkflowAuditRepository(ss),first=workflowAuditEntryTest_();repo.sheet.guard=lock;repo.appendConfirmedUnique(first);var next=Object.assign({},first,{receiptId:'WFR-UNPREDICTABLE-2',eventTimestamp:'2026-08-09T10:31:00.000Z',expiry:'2026-08-09T11:01:00.000Z'}),created=repo.appendConfirmedUnique(next),reused=repo.appendConfirmedUnique(Object.assign({},next,{receiptId:'WFR-UNPREDICTABLE-3',eventTimestamp:'2026-08-09T10:32:00.000Z',expiry:'2026-08-09T11:02:00.000Z'}));if(!created.created||reused.created||reused.entry.receiptId!==next.receiptId||repo.sheet.data.length!==2)throw new Error('Receipt expiry window authority failed.');return{success:true};});}
