/** Build 1018 Workflow Confirmation contracts. */
function workflowAuditMemory_(fail){return{rows:[],append:function(x){if(fail)throw new Error('audit failed');this.rows.push(JSON.parse(JSON.stringify(x)));},findByCorrelation:function(id){return this.rows.filter(function(x){return x.correlationId===id&&x.state==='CONFIRMED';});},findByReceipt:function(id){return this.rows.filter(function(x){return x.receiptId===id;});}};}
function workflowConfirmationFixture_(options){options=options||{};var repo=options.repo||workflowAuditMemory_(),now=options.now||new Date('2026-08-09T10:00:00Z'),permission=true;var service=JSKOS.WorkflowConfirmation.create({repository:repo,accessControl:{requireModuleOperation:function(){if(!permission)throw new Error('denied');}},prepareIntent:function(actionId,context){if(options.blocked)return{status:'BLOCKED'};return{status:'READY',actionId:actionId,destinationModule:'quotes',context:JSKOS.ClientContext.normalize(context),draftPayload:{actionId:actionId,actionType:'CREATE',companyId:String(context.companyId||'').toUpperCase(),personId:'',policyIds:[],destinationModule:'quotes'}};},actorProvider:function(){return options.actor===undefined?'user@example.com':options.actor;},uuidProvider:function(){return'ABC123';},clock:function(){return now;},hash:function(v){var h=0;for(var i=0;i<v.length;i++)h=(h*31+v.charCodeAt(i))>>>0;return'H'+h;}});return{service:service,repo:repo,setPermission:function(v){permission=v;}};}
function workflowReviewed_(company){return{actionId:'initiate-quote',actionType:'CREATE',companyId:company,personId:'',policyIds:[],destinationModule:'quotes'};}
function testBuild1018Confirmation(){var f=workflowConfirmationFixture_(),x=f.service.confirm('initiate-quote',{companyId:'com-1'},workflowReviewed_('COM-1'));if(x.state!=='CONFIRMED'||!x.receipt||f.repo.rows.length!==1||x.receipt.metadata.businessMutation!==false)throw new Error('Confirmation failed.');return{success:true};}
function testBuild1018TamperingAndBlocked(){var f=workflowConfirmationFixture_(),x=f.service.confirm('initiate-quote',{companyId:'COM-1'},workflowReviewed_('COM-2')),b=workflowConfirmationFixture_({blocked:true}).service.confirm('bad',{companyId:'COM-1'},{});if(x.state!=='BLOCKED'||x.receipt||b.state!=='BLOCKED')throw new Error('Tampering/blocked isolation failed.');return{success:true};}
function testBuild1018ActorAndBounds(){var f=workflowConfirmationFixture_({actor:''}),x=f.service.confirm('initiate-quote',{companyId:'COM-1'},workflowReviewed_('COM-1'));if(x.state!=='BLOCKED')throw new Error('Actor must be server-derived.');return{success:true};}
function testBuild1018ReplayAndAppendOnly(){var f=workflowConfirmationFixture_(),a=f.service.confirm('initiate-quote',{companyId:'COM-1'},workflowReviewed_('COM-1')),b=f.service.confirm('initiate-quote',{companyId:'COM-1'},workflowReviewed_('COM-1'));if(b.reasonCode!=='DUPLICATE_CONFIRMATION'||a.receipt.receiptId!==b.receipt.receiptId||f.repo.rows.length!==1)throw new Error('Replay protection failed.');return{success:true};}
function testBuild1018ReceiptAndHandoff(){var f=workflowConfirmationFixture_(),a=f.service.confirm('initiate-quote',{companyId:'COM-1'},workflowReviewed_('COM-1')),v=f.service.validateReceipt(a.receipt.receiptId,'initiate-quote',{companyId:'COM-1'}),h=f.service.recordHandoff(a.receipt.receiptId,'initiate-quote',{companyId:'COM-1'});if(!v.valid||h.state!=='HANDED_OFF'||f.repo.rows.length!==2)throw new Error('Receipt/handoff failed.');f.setPermission(false);try{f.service.validateReceipt(a.receipt.receiptId,'initiate-quote',{companyId:'COM-1'});throw new Error('permission not rechecked');}catch(e){if(e.message==='permission not rechecked')throw e;}return{success:true};}
function testBuild1018AuditFailure(){var f=workflowConfirmationFixture_({repo:workflowAuditMemory_(true)});try{f.service.confirm('initiate-quote',{companyId:'COM-1'},workflowReviewed_('COM-1'));throw new Error('audit failure ignored');}catch(e){if(e.message==='audit failure ignored')throw e;}return{success:true};}
function testBuild1018Expiry(){var repo=workflowAuditMemory_(),f=workflowConfirmationFixture_({repo:repo}),a=f.service.confirm('initiate-quote',{companyId:'COM-1'},workflowReviewed_('COM-1'));repo.rows[0].expiry='2020-01-01T00:00:00Z';if(f.service.validateReceipt(a.receipt.receiptId,'initiate-quote',{companyId:'COM-1'}).state!=='EXPIRED')throw new Error('Expiry failed.');return{success:true};}
function testBuild1018NoWrites(){if(typeof apiWorkflowConfirmationExecute==='function')throw new Error('Destination execution API introduced.');return{success:true};}
function testBuild1018Ui(){var content=renderClient360Ui().getContent();['Confirm reviewed intent','apiWorkflowConfirmationConfirm','apiWorkflowConfirmationHandoff','No destination business record','disabled=true'].forEach(function(m){if(content.indexOf(m)<0)throw new Error('Confirmation UI marker missing: '+m);});return{success:true};}
