/** JSK OS Build 1018 - durable workflow confirmation receipts. */
var JSKOS=JSKOS||{};
JSKOS.WorkflowConfirmation=Object.freeze((function(){'use strict';
  var STATES={CONFIRMED:true,HANDED_OFF:true,BLOCKED:true,EXPIRED:true,INVALID:true};
  function canonical_(value){if(Array.isArray(value))return'['+value.map(canonical_).join(',')+']';if(value&&typeof value==='object')return'{'+Object.keys(value).sort().map(function(k){return JSON.stringify(k)+':'+canonical_(value[k]);}).join(',')+'}';return JSON.stringify(value===undefined?null:value);}
  function defaultHash_(value){var bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8);return bytes.map(function(b){return('0'+((b+256)%256).toString(16)).slice(-2);}).join('');}
  function safe_(entry){return{receiptId:entry.receiptId,correlationId:entry.correlationId,eventTimestamp:entry.eventTimestamp,actionId:entry.actionId,destinationModule:entry.destinationModule,state:entry.state,expiry:entry.expiry,metadata:{build:1018,readOnly:true,businessMutation:false}};}
  function service(options){options=options||{};var repo=options.repository,prepare=options.prepareIntent,access=options.accessControl,actor=options.actorProvider,uuid=options.uuidProvider,clock=options.clock,hash=options.hash||defaultHash_;if(!repo||!prepare||!actor||!uuid)throw new Error('Workflow confirmation dependencies are unavailable.');
    function evaluate(actionId,context,reviewed){if(access)access.requireModuleOperation('client360','view');var intent=prepare(actionId,context);if(!intent||intent.status!=='READY')return{blocked:true};var serverDraft=intent.draftPayload||{},draftFingerprint=hash(canonical_(serverDraft)),reviewFingerprint=typeof reviewed==='string'?reviewed:hash(canonical_(reviewed||{}));if(reviewFingerprint!==draftFingerprint)return{blocked:true};var normalized=JSKOS.ClientContext.normalize(intent.context||context,{policyLimit:50});return{intent:intent,context:normalized,draftFingerprint:draftFingerprint,contextFingerprint:hash(canonical_({companyId:normalized.companyId,personId:normalized.personId,policyIds:normalized.policyIds}))};}
    return{
      confirm:function(actionId,context,reviewed){var checked=evaluate(actionId,context,reviewed);if(checked.blocked)return{state:'BLOCKED',reasonCode:'CONFIRMATION_UNAVAILABLE',receipt:null};var who=String(actor()||'').trim().toLowerCase();if(!who)return{state:'BLOCKED',reasonCode:'CONFIRMATION_UNAVAILABLE',receipt:null};var now=clock?clock():new Date(),correlation=hash(canonical_({actor:who,actionId:checked.intent.actionId,context:checked.contextFingerprint,draft:checked.draftFingerprint})),entry={receiptId:'WFR-'+uuid(),correlationId:correlation,eventTimestamp:now.toISOString(),actor:who,actionId:checked.intent.actionId,destinationModule:checked.intent.destinationModule,state:'CONFIRMED',companyId:checked.context.companyId,personId:checked.context.personId,policyIds:checked.context.policyIds.slice(0,50),draftFingerprint:checked.draftFingerprint,contextFingerprint:checked.contextFingerprint,expiry:new Date(now.getTime()+30*60000).toISOString(),parentReceiptId:'',metadata:{reviewRequired:true,sourceOwned:true}},result;try{result=repo.appendConfirmedUnique(entry);}catch(error){return{state:'INVALID',reasonCode:'AMBIGUOUS_EVIDENCE',receipt:null};}return{state:result.entry.state,reasonCode:result.created?'CONFIRMED':'DUPLICATE_CONFIRMATION',receipt:safe_(result.entry)};},
      getReceipt:function(id){var rows=repo.findByReceipt(String(id||''),100);if(!rows.length)return null;return safe_(rows[rows.length-1]);},
      validateReceipt:function(id,actionId,context){var rows=repo.findByReceipt(String(id||''),100);if(!rows.length)return{state:'INVALID',valid:false};var latest=rows[rows.length-1],now=clock?clock():new Date();if(latest.actionId!==String(actionId||'').trim().toLowerCase())return{state:'INVALID',valid:false};if(new Date(latest.expiry)<now)return{state:'EXPIRED',valid:false};var normalized=JSKOS.ClientContext.normalize(context||{},{policyLimit:50}),fingerprint=hash(canonical_({companyId:normalized.companyId,personId:normalized.personId,policyIds:normalized.policyIds}));if(fingerprint!==latest.contextFingerprint||['CONFIRMED','HANDED_OFF'].indexOf(latest.state)<0)return{state:'INVALID',valid:false};var checked=evaluate(actionId,context,latest.draftFingerprint);return checked.blocked?{state:'BLOCKED',valid:false}:{state:latest.state,valid:true,receipt:safe_(latest)};},
      recordHandoff:function(id,actionId,context){var valid=this.validateReceipt(id,actionId,context);if(!valid.valid)return valid;var now=clock?clock():new Date(),result;try{result=repo.appendHandoffUnique(String(id||''),{eventTimestamp:now.toISOString()},now);}catch(error){return{state:'INVALID',valid:false};}return{state:'HANDED_OFF',valid:true,receipt:safe_(result.entry)};}
    };}
  return{create:service,canonicalize:canonical_,STATES:Object.freeze(STATES)};
})());
