/** Build 1018 append-only Workflow_Audit evidence store. */
var JSK_WORKFLOW_AUDIT=Object.freeze({SHEET:'Workflow_Audit',HEADERS:Object.freeze(['Receipt ID','Correlation ID','Event Timestamp','Actor','Action ID','Destination Module','State','Company ID','Person ID','Policy IDs','Draft Fingerprint','Context Fingerprint','Expiry','Parent Receipt ID','Safe Metadata']),RECEIPT_COLUMN:1,CORRELATION_COLUMN:2,LOCK_TIMEOUT_MS:30000});
class WorkflowAuditStorageError extends Error{constructor(){super('Workflow audit storage is unavailable.');this.name='WorkflowAuditStorageError';this.code='WORKFLOW_AUDIT_STORAGE_FAILURE';}}
class WorkflowAuditRepository{
  constructor(spreadsheet){this.spreadsheet=spreadsheet||JSKOS.ConfigService.getSpreadsheet();this.sheet=this.initialize_();}
  lock_(){return LockService.getScriptLock();}
  withLock_(callback){var lock=this.lock_();lock.waitLock(JSK_WORKFLOW_AUDIT.LOCK_TIMEOUT_MS);try{return callback.call(this);}finally{if(typeof lock.hasLock!=='function'||lock.hasLock())lock.releaseLock();}}
  initialize_(){return this.withLock_(function(){var sheet=this.spreadsheet.getSheetByName(JSK_WORKFLOW_AUDIT.SHEET);if(!sheet){sheet=this.spreadsheet.insertSheet(JSK_WORKFLOW_AUDIT.SHEET);sheet.getRange(1,1,1,JSK_WORKFLOW_AUDIT.HEADERS.length).setValues([JSK_WORKFLOW_AUDIT.HEADERS.slice()]);sheet.setFrozenRows(1);}this.validateSchema_(sheet);return sheet;});}
  validateSchema_(sheet){if(!sheet||sheet.getLastColumn()!==JSK_WORKFLOW_AUDIT.HEADERS.length||sheet.getLastRow()<1)throw new Error('Workflow_Audit schema is incompatible.');var actual=sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0];if(actual.length!==JSK_WORKFLOW_AUDIT.HEADERS.length||actual.some(function(value,index){return String(value)!==JSK_WORKFLOW_AUDIT.HEADERS[index];}))throw new Error('Workflow_Audit schema is incompatible.');return true;}
  policyInfo_(value){var isArray=Array.isArray(value),values=isArray?value.slice():typeof value==='string'?(value===''?[]:value.split(',')):null,seen={},valid=Boolean(values);if(!values)return{values:[],count:0,valid:false};if(isArray&&values.some(function(item){return typeof item!=='string';}))valid=false;values=values.map(function(item){return String(item);});values.forEach(function(id){if(!/^[A-Z0-9][A-Z0-9._:-]{0,99}$/.test(id)||seen[id])valid=false;seen[id]=true;});if(values.length>50)valid=false;return{values:values,count:values.length,valid:valid};}
  validPolicyIds_(entry){var info=this.policyInfo_(entry&&entry.policyIds);return Boolean(entry&&entry.policyIdsValid!==false&&info.valid&&info.count<=50);}
  isCanonicalIso_(value){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)&&!isNaN(new Date(value).getTime())&&new Date(value).toISOString()===value;}
  isReceiptId_(value){return typeof value==='string'&&/^WFR-[A-F0-9]{24}$/.test(value);}
  isHash_(value){return typeof value==='string'&&/^[a-f0-9]{64}$/.test(value);}
  isActor_(value){return typeof value==='string'&&/^[a-z0-9._%+\-]+@[a-z0-9.-]+\.[a-z]{2,}$/.test(value);}
  isSlug_(value){return typeof value==='string'&&/^[a-z][a-z0-9-]{0,63}$/.test(value);}
  isEntityId_(value,optional){return typeof value==='string'&&((optional&&value==='')||/^[A-Z0-9][A-Z0-9._:-]{0,99}$/.test(value));}
  validBase_(entry){return Boolean(entry&&this.isReceiptId_(entry.receiptId)&&this.isHash_(entry.correlationId)&&this.isCanonicalIso_(entry.eventTimestamp)&&this.isActor_(entry.actor)&&this.isSlug_(entry.actionId)&&this.isSlug_(entry.destinationModule)&&this.isEntityId_(entry.companyId,true)&&this.isEntityId_(entry.personId,true)&&this.validPolicyIds_(entry)&&this.isHash_(entry.draftFingerprint)&&this.isHash_(entry.contextFingerprint)&&this.isCanonicalIso_(entry.expiry));}
  validHandoffShape_(entry){return Boolean(this.validBase_(entry)&&entry.state==='HANDED_OFF'&&this.isReceiptId_(entry.parentReceiptId));}
  row_(entry){var policies=this.policyInfo_(entry&&entry.policyIds),valid=entry&&entry.state==='CONFIRMED'?this.validConfirmation_(entry):entry&&entry.state==='HANDED_OFF'?this.validHandoffShape_(entry):this.validExecutionShape_(entry);if(!valid||!policies.valid)throw new Error('Invalid workflow audit evidence.');return[entry.receiptId,entry.correlationId,entry.eventTimestamp,entry.actor,entry.actionId,entry.destinationModule,entry.state,entry.companyId,entry.personId,policies.values.join(','),entry.draftFingerprint,entry.contextFingerprint,entry.expiry,entry.parentReceiptId,JSON.stringify(entry.metadata||{})];}
  sameList_(left,right){return(left||[]).join('\u0000')===(right||[]).join('\u0000');}
  isExpired_(expiry,now){var value=new Date(expiry).getTime(),trusted=now instanceof Date?now.getTime():Number(now);return isNaN(value)||isNaN(trusted)||value<=trusted;}
  validConfirmation_(entry){var eventTime=entry&&this.isCanonicalIso_(entry.eventTimestamp)?new Date(entry.eventTimestamp).getTime():NaN,expiry=entry&&this.isCanonicalIso_(entry.expiry)?new Date(entry.expiry).getTime():NaN;return Boolean(this.validBase_(entry)&&entry.state==='CONFIRMED'&&entry.parentReceiptId===''&&expiry>eventTime);}
  sameConfirmation_(existing,entry){return this.validConfirmation_(existing)&&existing.correlationId===entry.correlationId&&existing.actionId===entry.actionId&&existing.actor===entry.actor&&existing.destinationModule===entry.destinationModule&&existing.companyId===entry.companyId&&existing.personId===entry.personId&&this.sameList_(existing.policyIds,entry.policyIds)&&existing.contextFingerprint===entry.contextFingerprint&&existing.draftFingerprint===entry.draftFingerprint;}
  validHandoffFor_(handoff,parent){var eventTime=handoff&&this.isCanonicalIso_(handoff.eventTimestamp)?new Date(handoff.eventTimestamp).getTime():NaN,parentTime=parent&&this.isCanonicalIso_(parent.eventTimestamp)?new Date(parent.eventTimestamp).getTime():NaN,expiry=parent&&this.isCanonicalIso_(parent.expiry)?new Date(parent.expiry).getTime():NaN;return Boolean(this.validHandoffShape_(handoff)&&this.validConfirmation_(parent)&&handoff.receiptId===parent.receiptId&&handoff.parentReceiptId===parent.receiptId&&handoff.correlationId===parent.correlationId&&handoff.actor===parent.actor&&handoff.actionId===parent.actionId&&handoff.destinationModule===parent.destinationModule&&handoff.companyId===parent.companyId&&handoff.personId===parent.personId&&this.sameList_(handoff.policyIds,parent.policyIds)&&handoff.draftFingerprint===parent.draftFingerprint&&handoff.contextFingerprint===parent.contextFingerprint&&handoff.expiry===parent.expiry&&eventTime>=parentTime&&eventTime<expiry);}
  validateCorrelatedHistory_(history,entry){var allowed=['CONFIRMED','HANDED_OFF','EXECUTION_STARTED','DESTINATION_COMMITTED'],confirmed=history.filter(function(row){return row.state==='CONFIRMED';}),handed=history.filter(function(row){return row.state==='HANDED_OFF';}),unexpected=history.filter(function(row){return allowed.indexOf(row.state)<0;}),receiptCounts={};if(unexpected.length||confirmed.some(function(row){return!this.sameConfirmation_(row,entry);},this))throw new Error('Contradictory workflow confirmation evidence.');confirmed.forEach(function(row){receiptCounts[row.receiptId]=(receiptCounts[row.receiptId]||0)+1;});if(Object.keys(receiptCounts).some(function(id){return receiptCounts[id]!==1;}))throw new Error('Duplicate workflow receipt evidence.');handed.forEach(function(row){var parents=confirmed.filter(function(parent){return parent.receiptId===row.receiptId;});if(parents.length!==1||!this.validHandoffFor_(row,parents[0]))throw new Error('Contradictory workflow handoff evidence.');},this);var lifecycleCounts={};handed.forEach(function(row){lifecycleCounts[row.receiptId]=(lifecycleCounts[row.receiptId]||0)+1;});if(Object.keys(lifecycleCounts).some(function(id){return lifecycleCounts[id]!==1;}))throw new Error('Ambiguous workflow handoff evidence.');confirmed.forEach(function(parent){var globalHistory=this.findExactUnlocked_(JSK_WORKFLOW_AUDIT.RECEIPT_COLUMN,parent.receiptId),globalConfirmed=globalHistory.filter(function(row){return row.state==='CONFIRMED';}),globalHanded=globalHistory.filter(function(row){return row.state==='HANDED_OFF';}),execution=globalHistory.filter(function(row){return['EXECUTION_STARTED','DESTINATION_COMMITTED'].indexOf(row.state)>=0;});if(globalHistory.some(function(row){return row.correlationId!==entry.correlationId;})||globalConfirmed.length!==1||globalHanded.length>1||globalHistory.length!==globalConfirmed.length+globalHanded.length+execution.length)throw new Error('Ambiguous global workflow receipt evidence.');if(globalHanded.length&&!this.validHandoffFor_(globalHanded[0],globalConfirmed[0]))throw new Error('Contradictory global workflow handoff evidence.');if(execution.some(function(row){return!this.validExecutionFor_(row,globalConfirmed[0]);},this))throw new Error('Contradictory execution evidence.');},this);return confirmed;}
  appendUnlocked_(entry){if(['CONFIRMED','HANDED_OFF','EXECUTION_STARTED','DESTINATION_COMMITTED'].indexOf(entry&&entry.state)<0)throw new Error('Invalid workflow audit state.');this.validateSchema_(this.sheet);this.sheet.appendRow(this.row_(entry));SpreadsheetApp.flush();return entry;}
  append(){throw new Error('Generic workflow audit append is not permitted.');}
  entryFromRow_(r){var rawPolicies=r[9]===null||r[9]===undefined?'':r[9],policies=this.policyInfo_(rawPolicies),metadata={};try{metadata=r[14]?JSON.parse(r[14]):{};}catch(error){metadata={invalid:true};}return{receiptId:r[0],correlationId:r[1],eventTimestamp:r[2],actor:r[3],actionId:r[4],destinationModule:r[5],state:r[6],companyId:r[7],personId:r[8],policyIds:policies.values,policyIdsValid:policies.valid,policyIdsRawCount:policies.count,draftFingerprint:r[10],contextFingerprint:r[11],expiry:r[12],parentReceiptId:r[13],metadata:metadata};}
  findExactUnlocked_(column,id){this.validateSchema_(this.sheet);var last=this.sheet.getLastRow(),needle=String(id||'');if(last<2||!needle)return[];var finder=this.sheet.getRange(2,column,last-1,1).createTextFinder(needle).matchEntireCell(true).matchCase(true),ranges=finder.findAll().sort(function(a,b){return a.getRow()-b.getRow();}),self=this;return ranges.map(function(range){return self.entryFromRow_(self.sheet.getRange(range.getRow(),1,1,JSK_WORKFLOW_AUDIT.HEADERS.length).getValues()[0]);});}
  findByCorrelation(id){return this.findExactUnlocked_(JSK_WORKFLOW_AUDIT.CORRELATION_COLUMN,id).filter(function(x){return x.state==='CONFIRMED';});}
  findByReceipt(id){return this.findExactUnlocked_(JSK_WORKFLOW_AUDIT.RECEIPT_COLUMN,id);}
  appendConfirmedUnique(entry){return this.withLock_(function(){if(!this.validConfirmation_(entry))throw new Error('Invalid workflow confirmation evidence.');var eventTime=new Date(entry.eventTimestamp).getTime(),history=this.findExactUnlocked_(JSK_WORKFLOW_AUDIT.CORRELATION_COLUMN,entry.correlationId),matches=this.validateCorrelatedHistory_(history,entry),active=matches.filter(function(existing){return!this.isExpired_(existing.expiry,eventTime);},this);if(active.length>1)throw new Error('Ambiguous workflow confirmation evidence.');if(active.length===1)return{created:false,entry:active[0]};if(this.findExactUnlocked_(JSK_WORKFLOW_AUDIT.RECEIPT_COLUMN,entry.receiptId).length)throw new Error('Workflow receipt ID collision.');return{created:true,entry:this.appendUnlocked_(entry)};});}
  appendHandoffUnique(receiptId,event,now){return this.withLock_(function(){var history=this.findByReceipt(receiptId),confirmed=history.filter(function(x){return x.state==='CONFIRMED';}),handed=history.filter(function(x){return x.state==='HANDED_OFF';}),invalid=history.filter(function(x){return['CONFIRMED','HANDED_OFF','EXECUTION_STARTED','DESTINATION_COMMITTED'].indexOf(x.state)<0;});if(confirmed.length!==1||handed.length>1||invalid.length||!this.validConfirmation_(confirmed[0]))throw new Error('Ambiguous workflow receipt lifecycle.');var parent=confirmed[0];if(handed.length===1){if(!this.validHandoffFor_(handed[0],parent))throw new Error('Contradictory workflow handoff evidence.');return{created:false,entry:handed[0]};}if(history.some(function(x){return['EXECUTION_STARTED','DESTINATION_COMMITTED'].indexOf(x.state)>=0;}))throw new Error('Execution evidence exists without handoff.');if(this.isExpired_(parent.expiry,now))throw new Error('Workflow receipt expired.');var next=Object.assign({},event,{receiptId:parent.receiptId,correlationId:parent.correlationId,actor:parent.actor,actionId:parent.actionId,destinationModule:parent.destinationModule,companyId:parent.companyId,personId:parent.personId,policyIds:parent.policyIds.slice(),draftFingerprint:parent.draftFingerprint,contextFingerprint:parent.contextFingerprint,expiry:parent.expiry,state:'HANDED_OFF',parentReceiptId:parent.receiptId});return{created:true,entry:this.appendUnlocked_(next)};});}
  assertAuthorityLock_(lock){if(!lock||typeof lock.hasLock!=='function'||!lock.hasLock())throw new Error('Authoritative execution lock is required.');}
  validExecutionShape_(entry){var metadata=entry&&entry.metadata||{},keys=Object.keys(metadata).sort(),expected=entry&&entry.state==='EXECUTION_STARTED'?['build','payloadFingerprint']:['build','destinationRecordId','destinationType','payloadFingerprint'];if(!this.validBase_(entry)||['EXECUTION_STARTED','DESTINATION_COMMITTED'].indexOf(entry.state)<0||!this.isReceiptId_(entry.parentReceiptId)||keys.join('|')!==expected.sort().join('|')||metadata.build!==1019||!this.isHash_(metadata.payloadFingerprint))return false;if(entry.state==='DESTINATION_COMMITTED'&&(metadata.destinationType!=='quote'||typeof metadata.destinationRecordId!=='string'||!/^QTE-[A-F0-9]{8}$/.test(metadata.destinationRecordId)))return false;return JSON.stringify(metadata).length<=512;}
  validExecutionFor_(entry,parent){var eventTime=entry&&this.isCanonicalIso_(entry.eventTimestamp)?new Date(entry.eventTimestamp).getTime():NaN,parentTime=parent&&this.isCanonicalIso_(parent.eventTimestamp)?new Date(parent.eventTimestamp).getTime():NaN,expiry=parent&&this.isCanonicalIso_(parent.expiry)?new Date(parent.expiry).getTime():NaN,base=this.validExecutionShape_(entry)&&this.validConfirmation_(parent)&&entry.receiptId===parent.receiptId&&entry.parentReceiptId===parent.receiptId&&entry.correlationId===parent.correlationId&&entry.actor===parent.actor&&entry.actionId===parent.actionId&&entry.destinationModule===parent.destinationModule&&entry.companyId===parent.companyId&&entry.personId===parent.personId&&this.sameList_(entry.policyIds,parent.policyIds)&&entry.draftFingerprint===parent.draftFingerprint&&entry.contextFingerprint===parent.contextFingerprint&&entry.expiry===parent.expiry&&eventTime>=parentTime;return Boolean(base&&(entry.state==='EXECUTION_STARTED'?eventTime<expiry:true));}
  getExecutionAuthorityLocked(receiptId,now,lock){this.assertAuthorityLock_(lock);var history=this.findByReceipt(receiptId),confirmed=history.filter(function(x){return x.state==='CONFIRMED';}),handed=history.filter(function(x){return x.state==='HANDED_OFF';}),started=history.filter(function(x){return x.state==='EXECUTION_STARTED';}),committed=history.filter(function(x){return x.state==='DESTINATION_COMMITTED';}),invalid=history.filter(function(x){return['CONFIRMED','HANDED_OFF','EXECUTION_STARTED','DESTINATION_COMMITTED'].indexOf(x.state)<0;});if(confirmed.length!==1||handed.length!==1||started.length>1||committed.length>1||invalid.length)throw new Error('Ambiguous workflow execution lifecycle.');var parent=confirmed[0],handoffTime=handed.length?new Date(handed[0].eventTimestamp).getTime():NaN,startTime=started.length?new Date(started[0].eventTimestamp).getTime():NaN,commitTime=committed.length?new Date(committed[0].eventTimestamp).getTime():NaN;if(!this.validConfirmation_(parent)||!this.validHandoffFor_(handed[0],parent)||started.some(function(x){return!this.validExecutionFor_(x,parent);},this)||committed.some(function(x){return!this.validExecutionFor_(x,parent);},this)||committed.length&&!started.length||started.length&&startTime<handoffTime||committed.length&&commitTime<startTime)throw new Error('Workflow execution authority is unavailable.');if(started.length&&committed.length&&started[0].metadata.payloadFingerprint!==committed[0].metadata.payloadFingerprint)throw new Error('Contradictory workflow execution evidence.');return{confirmation:parent,handoff:handed[0],started:started[0]||null,committed:committed[0]||null,expired:this.isExpired_(parent.expiry,now)};}
  executionEvent_(authority,state,metadata,now){var parent=authority.confirmation;return{receiptId:parent.receiptId,correlationId:parent.correlationId,eventTimestamp:now.toISOString(),actor:parent.actor,actionId:parent.actionId,destinationModule:parent.destinationModule,state:state,companyId:parent.companyId,personId:parent.personId,policyIds:parent.policyIds.slice(),draftFingerprint:parent.draftFingerprint,contextFingerprint:parent.contextFingerprint,expiry:parent.expiry,parentReceiptId:parent.receiptId,metadata:metadata};}
  appendExecutionStartedLocked(authority,payloadFingerprint,now,lock){this.assertAuthorityLock_(lock);if(this.isExpired_(authority.confirmation.expiry,now))throw new Error('Workflow receipt expired.');if(authority.committed)return{created:false,entry:authority.committed};if(authority.started){if(authority.started.metadata.payloadFingerprint!==payloadFingerprint)throw new Error('Workflow execution payload mismatch.');return{created:false,entry:authority.started};}var entry=this.executionEvent_(authority,'EXECUTION_STARTED',{build:1019,payloadFingerprint:payloadFingerprint},now);return{created:true,entry:this.appendUnlocked_(entry)};}
  appendDestinationCommittedLocked(authority,payloadFingerprint,quoteId,now,lock){this.assertAuthorityLock_(lock);var current=this.getExecutionAuthorityLocked(authority.confirmation.receiptId,now,lock);if(!current.started||current.started.metadata.payloadFingerprint!==payloadFingerprint)throw new Error('Workflow execution start evidence is unavailable.');if(current.committed){if(current.committed.metadata.payloadFingerprint!==payloadFingerprint||current.committed.metadata.destinationRecordId!==quoteId)throw new Error('Contradictory destination evidence.');return{created:false,entry:current.committed};}var entry=this.executionEvent_(current,'DESTINATION_COMMITTED',{build:1019,destinationType:'quote',destinationRecordId:quoteId,payloadFingerprint:payloadFingerprint},now);this.row_(entry);try{return{created:true,entry:this.appendUnlocked_(entry)};}catch(error){throw new WorkflowAuditStorageError();}}
}
