/** JSK OS Build 1024 - Revenue and durable payment management. */
var JSK_REVENUE_SCHEMA=Object.freeze({VERSION:2,SHEET_NAME:'Revenue',KEY:'JSK_OS_REVENUE_SCHEMA_VERSION',HEADERS:Object.freeze(['Revenue ID','Invoice Number','Policy ID','Company ID','Insurer Name','Policy Number','Business Type','Premium Amount','Commission Rate','Expected Commission','GST Amount','TDS Amount','Net Receivable','Amount Received','Outstanding Amount','Payment Status','Expected Date','Received Date','Reconciliation Reference','Assigned Owner','Notes','Created At','Created By','Updated At','Updated By','Record Version','Is Deleted']),STATUS:Object.freeze(['Expected','Invoiced','Partially Received','Received','Overdue','Disputed','Written Off'])});
var JSK_REVENUE_PAYMENT_SCHEMA=Object.freeze({VERSION:2,SHEET_NAME:'Revenue_Payments',LEGACY_HEADERS:Object.freeze(['Payment ID','Revenue ID','Payment Date','Amount','Reference','Notes','Created At','Created By']),CONTROL_HEADERS:Object.freeze(['Request Key','Payload Fingerprint','State','Completed At','Completed By','Recovery At','Recovery By','Last Error']),KEY:'JSK_OS_REVENUE_PAYMENT_SCHEMA_VERSION'});

function revenueHash_(value){var bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(value),Utilities.Charset.UTF_8);return bytes.map(function(x){return('0'+((x+256)%256).toString(16)).slice(-2);}).join('');}
function revenueDay_(value){return Utilities.formatDate(value instanceof Date?value:new Date(value),JSKOS.Config.APP.TIMEZONE,'yyyy-MM-dd');}
function revenueServerActor_(context){return JSKOS.RevenuePayment.email(context&&context.email);}
function revenueLockHeld_(lock){if(!lock||(typeof lock.hasLock==='function'&&!lock.hasLock()))throw new Error('Authoritative Revenue lock is required.');}
function revenueProtected_(data,creating){var protectedFields=['amountReceived','outstandingAmount','receivedDate','reconciliationReference'];protectedFields.forEach(function(key){if(Object.prototype.hasOwnProperty.call(data||{},key))throw new Error(key+' is ledger-derived and cannot be edited.');});if(Object.prototype.hasOwnProperty.call(data||{},'paymentStatus')&&['Received','Partially Received'].indexOf(String(data.paymentStatus))!==-1)throw new Error('Payment Status is ledger-derived and cannot be edited.');if(creating&&Object.prototype.hasOwnProperty.call(data||{},'recordVersion'))throw new Error('Record Version cannot be supplied.');}

function migrateRevenueDatabase(){var context=JSKOS.AccessControl.requireModuleOperation('revenue','reconcile');return migrateRevenueDatabaseWithOptions_({actor:revenueServerActor_(context)});}
function migrateRevenueDatabaseWithOptions_(options){
  options=options||{};var actor=JSKOS.RevenuePayment.email(options.actor),lock=(options.lockProvider||function(){return LockService.getScriptLock();})(),fault=options.fault||function(){},flush=options.flush||function(){if(typeof SpreadsheetApp!=='undefined')SpreadsheetApp.flush();},acquired=false;
  function same_(a,b){return a.length===b.length&&a.every(function(value,index){return value===b[index];});}
  function headers_(sheet){return sheet&&sheet.getLastColumn()?sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0]:[];}
  function cellSame_(a,b){if(a instanceof Date||b instanceof Date)return a instanceof Date&&b instanceof Date&&a.getTime()===b.getTime();return typeof a===typeof b&&a===b;}
  function rowSame_(a,b){return a.length===b.length&&a.every(function(value,index){return cellSame_(value,b[index]);});}
  function migrationRequest_(row){return{revenueId:String(row.revenueId).trim().toUpperCase(),amountPaise:JSKOS.RevenuePayment.paymentPaise(row.amount),dateIdentity:revenueDay_(row.paymentDate),reference:String(row.reference||'').trim(),notes:String(row.notes||'').trim()};}
  try{try{lock.waitLock(30000);acquired=true;}catch(error){var busy=new Error('Revenue migration is busy.');busy.code='REVENUE_MIGRATION_LOCK_UNAVAILABLE';throw busy;}
    var ss=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet(),props=options.properties||PropertiesService.getScriptProperties(),legacy=JSK_REVENUE_PAYMENT_SCHEMA.LEGACY_HEADERS.slice(),canonical=legacy.concat(JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS),existingRevenue=ss.getSheetByName(JSK_REVENUE_SCHEMA.SHEET_NAME),existingPayments=ss.getSheetByName(JSK_REVENUE_PAYMENT_SCHEMA.SHEET_NAME),revenueHeaders=headers_(existingRevenue),paymentHeaders=headers_(existingPayments),revenueEmpty=!revenueHeaders.some(String),paymentEmpty=!paymentHeaders.some(String),legacyLayout=same_(paymentHeaders,legacy),canonicalLayout=same_(paymentHeaders,canonical);
    if(!paymentEmpty&&!legacyLayout&&!canonicalLayout)throw new Error('Revenue payment sheet schema is unsupported.');
    if(!revenueEmpty){var revenueHeaderSeen={};revenueHeaders.forEach(function(header){if(!header||revenueHeaderSeen[header])throw new Error('Revenue sheet schema is unsupported.');revenueHeaderSeen[header]=true;});if(revenueHeaders.indexOf('Revenue ID')===-1)throw new Error('Revenue sheet schema is unsupported.');}
    var finalRevenueHeaders=revenueEmpty?JSK_REVENUE_SCHEMA.HEADERS.slice():revenueHeaders.slice();JSK_REVENUE_SCHEMA.HEADERS.forEach(function(header){if(finalRevenueHeaders.indexOf(header)===-1)finalRevenueHeaders.push(header);});
    var revenueMapper=Object.create(RevenueRepository.prototype);revenueMapper.h=revenueHeaders.slice(),revenues=[],byRevenue={};if(existingRevenue&&!revenueEmpty&&existingRevenue.getLastRow()>=2){revenues=existingRevenue.getRange(2,1,existingRevenue.getLastRow()-1,revenueHeaders.length).getValues().map(revenueMapper.obj_.bind(revenueMapper));}revenues.forEach(function(row){var id=String(row.revenueId||'').trim().toUpperCase();if(!id||byRevenue[id])throw new Error('Revenue ID is missing or duplicated.');row.revenueId=id;JSKOS.RevenuePayment.financial(row);JSKOS.RevenuePayment.moneyPaise(row.amountReceived||0);byRevenue[id]=row;});
    var originalEight=existingPayments&&existingPayments.getLastRow()>=2?existingPayments.getRange(2,1,existingPayments.getLastRow()-1,legacy.length).getValues():[],rawWidth=canonicalLayout?canonical.length:legacy.length,rawPayments=existingPayments&&existingPayments.getLastRow()>=2?existingPayments.getRange(2,1,existingPayments.getLastRow()-1,rawWidth).getValues():[],paymentMapper=Object.create(RevenuePaymentRepository.prototype);paymentMapper.h=canonical.slice();var plannedRows=[],backfills=[],ids={},keys={};
    rawPayments.forEach(function(raw,index){var padded=raw.slice();while(padded.length<canonical.length)padded.push('');var row=paymentMapper.obj_(padded),id=String(row.paymentId||'').trim().toUpperCase(),rid=String(row.revenueId||'').trim().toUpperCase(),suffix=padded.slice(legacy.length),hasControl=suffix.some(function(value){return String(value===null||value===undefined?'':value).trim()!=='';});if(!id||ids[id])throw new Error('Legacy Payment ID is missing or duplicated.');ids[id]=true;if(!byRevenue[rid])throw new Error('Legacy payment has an orphan Revenue ID.');JSKOS.RevenuePayment.paymentPaise(row.amount);JSKOS.RevenuePayment.dateDay(row.paymentDate,true);if(/^[=+\-@]/.test(String(row.reference||'').trim())||/^[=+\-@]/.test(String(row.notes||'').trim())||/^[=+\-@]/.test(String(row.createdBy||'').trim()))throw new Error('Legacy payment contains formula-like text.');var acceptedAt=row.createdAt instanceof Date?row.createdAt:new Date(row.createdAt);if(isNaN(acceptedAt.getTime()))throw new Error('Legacy payment acceptance time is invalid.');row.paymentId=id;row.revenueId=rid;if(hasControl){var valid=JSKOS.RevenuePayment.validateRows([row],revenueHash_)[0];if(keys[valid.requestKey])throw new Error('Duplicate payment request evidence.');keys[valid.requestKey]=true;plannedRows.push(row);}else{var digest=revenueHash_(JSON.stringify([index+2].concat(raw.slice(0,legacy.length).map(function(value){return value instanceof Date?value.toISOString():value;})))),requestKey='RPK-MIG-'+digest.slice(0,24).toUpperCase(),request=migrationRequest_(row),patch={requestKey:requestKey,payloadFingerprint:JSKOS.RevenuePayment.fingerprint(request,revenueHash_),state:'COMPLETED',completedAt:row.createdAt,completedBy:row.createdBy,recoveryAt:'',recoveryBy:'',lastError:''};if(keys[requestKey])throw new Error('Duplicate payment request evidence.');keys[requestKey]=true;backfills.push({paymentId:id,patch:patch});plannedRows.push(Object.assign({},row,patch,{legacy:true}));}});
    JSKOS.RevenuePayment.validateRows(plannedRows,revenueHash_);plannedRows.forEach(function(row,index){if(/^RPK-MIG-/.test(row.requestKey)&&!/^PAY-MIG-/.test(row.paymentId)&&String(row.reference||'')!=='Legacy received balance'){var original=rawPayments[index].slice(0,legacy.length),expectedKey='RPK-MIG-'+revenueHash_(JSON.stringify([index+2].concat(original.map(function(value){return value instanceof Date?value.toISOString():value;})))).slice(0,24).toUpperCase();if(row.requestKey!==expectedKey)throw new Error('Legacy migration identity is contradictory.');}});
    plannedRows.forEach(function(row){if(/^PAY-MIG-/.test(row.paymentId)||String(row.reference||'')==='Legacy received balance'){var request=migrationRequest_(row),digest=revenueHash_('BASELINE|'+request.revenueId+'|'+request.amountPaise),expectedId='PAY-MIG-'+digest.slice(0,12).toUpperCase(),expectedKey='RPK-MIG-'+digest.slice(0,24).toUpperCase(),expectedFingerprint=JSKOS.RevenuePayment.fingerprint(request,revenueHash_);if(row.paymentId!==expectedId||row.requestKey!==expectedKey||String(row.payloadFingerprint).toLowerCase()!==expectedFingerprint)throw new Error('Synthetic migration identity collision.');}});
    var synthetic=[],aggregates={};revenues.forEach(function(revenue){if(revenue.isDeleted)return;var rid=revenue.revenueId,target=plannedRows.filter(function(row){return row.revenueId===rid;}),normalized=JSKOS.RevenuePayment.validateRows(target,revenueHash_,rid),sum=normalized.reduce(function(total,row){var next=total+row.amountPaise;if(!Number.isSafeInteger(next))throw new Error('Legacy payment total is unsafe.');return next;},0),legacyReceived=JSKOS.RevenuePayment.moneyPaise(revenue.amountReceived||0);if(legacyReceived>sum){var difference=legacyReceived-sum,digest=revenueHash_('BASELINE|'+rid+'|'+difference),paymentId='PAY-MIG-'+digest.slice(0,12).toUpperCase(),requestKey='RPK-MIG-'+digest.slice(0,24).toUpperCase(),collision=plannedRows.filter(function(row){return row.paymentId===paymentId||row.requestKey===requestKey;});var dateValue=revenue.receivedDate||revenue.updatedAt||revenue.createdAt;if(!dateValue)throw new Error('Synthetic balance date is unavailable.');var date=revenueDay_(dateValue),request={revenueId:rid,amountPaise:difference,dateIdentity:date,reference:'Legacy received balance',notes:''},fingerprint=JSKOS.RevenuePayment.fingerprint(request,revenueHash_);if(collision.length){if(collision.length!==1||collision[0].revenueId!==rid||JSKOS.RevenuePayment.paymentPaise(collision[0].amount)!==difference||String(collision[0].payloadFingerprint).toLowerCase()!==fingerprint)throw new Error('Synthetic migration identity collision.');}else{var now=new Date(),row={paymentId:paymentId,revenueId:rid,paymentDate:date,amount:difference/100,reference:'Legacy received balance',notes:'',createdAt:now,createdBy:actor,requestKey:requestKey,payloadFingerprint:fingerprint,state:'COMPLETED',completedAt:now,completedBy:actor,recoveryAt:'',recoveryBy:'',lastError:'',legacy:true};synthetic.push(row);plannedRows.push(row);target.push(row);}}aggregates[rid]=JSKOS.RevenuePayment.aggregate(JSKOS.RevenuePayment.validateRows(target,revenueHash_,rid),revenue);});
    var revenueHeadersReady=existingRevenue&&!revenueEmpty&&same_(revenueHeaders,finalRevenueHeaders),paymentHeadersReady=existingPayments&&canonicalLayout,rowsReady=backfills.length===0&&synthetic.length===0,aggregatesReady=revenues.filter(function(row){return !row.isDeleted;}).every(function(row){return JSKOS.RevenuePayment.aggregateMatches(row,aggregates[row.revenueId]);});if(Number(props.getProperty(JSK_REVENUE_SCHEMA.KEY)||0)>=2&&Number(props.getProperty(JSK_REVENUE_PAYMENT_SCHEMA.KEY)||0)>=2&&revenueHeadersReady&&paymentHeadersReady&&rowsReady&&aggregatesReady)return{success:true,schemaVersion:2,paymentSchemaVersion:2};
    var revenueSheet=existingRevenue||ss.insertSheet(JSK_REVENUE_SCHEMA.SHEET_NAME),paymentSheet=existingPayments||ss.insertSheet(JSK_REVENUE_PAYMENT_SCHEMA.SHEET_NAME);if(revenueEmpty)revenueSheet.getRange(1,1,1,finalRevenueHeaders.length).setValues([finalRevenueHeaders]);else JSK_REVENUE_SCHEMA.HEADERS.forEach(function(header){if(revenueHeaders.indexOf(header)===-1){revenueSheet.getRange(1,revenueSheet.getLastColumn()+1).setValue(header);revenueHeaders.push(header);}});if(paymentEmpty)paymentSheet.getRange(1,1,1,canonical.length).setValues([canonical]);else if(legacyLayout)paymentSheet.getRange(1,legacy.length+1,1,JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS.length).setValues([JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS.slice()]);flush();if(!JSK_REVENUE_SCHEMA.HEADERS.every(function(header){return headers_(revenueSheet).indexOf(header)!==-1;})||!same_(headers_(paymentSheet),canonical))throw new Error('Canonical migration headers were not persisted.');fault('afterCanonicalHeaderWrite');
    var revenueRepo=new RevenueRepository({spreadsheet:ss,skipMigration:true}),paymentRepo=new RevenuePaymentRepository({spreadsheet:ss,skipMigration:true});backfills.forEach(function(item){paymentRepo.backfillUnderLock(item.paymentId,item.patch,lock);fault('afterControlRowBackfill',{paymentId:item.paymentId});});synthetic.forEach(function(row){var existing=paymentRepo.all().filter(function(item){return item.paymentId===row.paymentId||item.requestKey===row.requestKey;});if(existing.length){if(existing.length!==1||existing[0].revenueId!==row.revenueId||JSKOS.RevenuePayment.paymentPaise(existing[0].amount)!==JSKOS.RevenuePayment.paymentPaise(row.amount)||String(existing[0].payloadFingerprint).toLowerCase()!==row.payloadFingerprint)throw new Error('Synthetic migration identity collision.');}else paymentRepo.appendAcceptedUnderLock(row,lock);fault('afterSyntheticAppend',{paymentId:row.paymentId});});revenues.forEach(function(revenue){if(revenue.isDeleted)return;revenueRepo.applyAggregateUnderLock(revenue.revenueId,aggregates[revenue.revenueId],actor,new Date(),lock);fault('afterAggregateRepair',{revenueId:revenue.revenueId});});flush();
    if(!same_(headers_(paymentSheet),canonical)||!JSK_REVENUE_SCHEMA.HEADERS.every(function(header){return headers_(revenueSheet).indexOf(header)!==-1;}))throw new Error('Canonical migration headers failed verification.');var persistedEight=paymentSheet.getLastRow()>=2?paymentSheet.getRange(2,1,paymentSheet.getLastRow()-1,legacy.length).getValues().slice(0,originalEight.length):[];if(persistedEight.length!==originalEight.length||!persistedEight.every(function(row,index){return rowSame_(row,originalEight[index]);}))throw new Error('Legacy payment cells changed during migration.');var verifiedPayments=paymentRepo.all(),verifiedRows=JSKOS.RevenuePayment.validateRows(verifiedPayments,revenueHash_);if(verifiedRows.length!==plannedRows.length)throw new Error('Migrated payment row count is incorrect.');synthetic.forEach(function(row){var found=verifiedPayments.filter(function(item){return item.paymentId===row.paymentId&&item.requestKey===row.requestKey&&item.revenueId===row.revenueId&&JSKOS.RevenuePayment.paymentPaise(item.amount)===JSKOS.RevenuePayment.paymentPaise(row.amount)&&String(item.payloadFingerprint).toLowerCase()===row.payloadFingerprint;});if(found.length!==1)throw new Error('Synthetic migration row failed verification.');});revenues.forEach(function(revenue){if(revenue.isDeleted)return;var persisted=revenueRepo.find(revenue.revenueId,true);if(!JSKOS.RevenuePayment.aggregateMatches(persisted,aggregates[revenue.revenueId]))throw new Error('Revenue aggregate failed migration verification.');});
    fault('beforePropertyCommit');props.setProperty(JSK_REVENUE_SCHEMA.KEY,'2');props.setProperty(JSK_REVENUE_PAYMENT_SCHEMA.KEY,'2');if(String(props.getProperty(JSK_REVENUE_SCHEMA.KEY))!=='2'||String(props.getProperty(JSK_REVENUE_PAYMENT_SCHEMA.KEY))!=='2')throw new Error('Revenue schema properties failed verification.');return{success:true,schemaVersion:2,paymentSchemaVersion:2};
  }finally{if(acquired)lock.releaseLock();}
}
function revenueMigrationRequired_(){var error=new Error('Revenue schema migration is required. Ask an Administrator to run Revenue migration.');error.code='REVENUE_MIGRATION_REQUIRED';error.data={state:'UNAVAILABLE',action:'ADMIN_MIGRATION_REQUIRED'};return error;}
function ensureBuild1011Revenue(options){options=options||{};var ss=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet(),revenue=ss.getSheetByName(JSK_REVENUE_SCHEMA.SHEET_NAME),payments=ss.getSheetByName(JSK_REVENUE_PAYMENT_SCHEMA.SHEET_NAME),props=options.properties||PropertiesService.getScriptProperties(),version=Number(props.getProperty(JSK_REVENUE_SCHEMA.KEY)||0),paymentVersion=Number(props.getProperty(JSK_REVENUE_PAYMENT_SCHEMA.KEY)||0),canonical=JSK_REVENUE_PAYMENT_SCHEMA.LEGACY_HEADERS.concat(JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS);if(!revenue||!payments||version<2||paymentVersion<2)throw revenueMigrationRequired_();var revenueHeaders=revenue.getRange(1,1,1,revenue.getLastColumn()).getDisplayValues()[0],paymentHeaders=payments.getRange(1,1,1,payments.getLastColumn()).getDisplayValues()[0],revenueReady=JSK_REVENUE_SCHEMA.HEADERS.every(function(header){return revenueHeaders.indexOf(header)!==-1;}),paymentsReady=paymentHeaders.length===canonical.length&&paymentHeaders.every(function(header,index){return header===canonical[index];});if(!revenueReady||!paymentsReady)throw revenueMigrationRequired_();return{success:true,schemaVersion:2,paymentSchemaVersion:2};}

class RevenueRepository{
  constructor(options){options=options||{};this.spreadsheet=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet();if(!options.skipMigration&&!options.readOnly)ensureBuild1011Revenue({spreadsheet:this.spreadsheet,actor:options.actor});this.sheet=this.spreadsheet.getSheetByName(JSK_REVENUE_SCHEMA.SHEET_NAME);if(!this.sheet)throw new Error('Revenue sheet is unavailable.');this.h=this.sheet.getRange(1,1,1,this.sheet.getLastColumn()).getDisplayValues()[0];}
  calc_(x){var financial=JSKOS.RevenuePayment.financial(x),received=JSKOS.RevenuePayment.moneyPaise(x.amountReceived||0);if(financial.derivedExpected)x.expectedCommission=financial.expectedCommission;x.netReceivable=financial.netReceivable;x.amountReceived=received/100;x.outstandingAmount=Math.max(0,financial.netReceivablePaise-received)/100;if(received>0&&received<financial.netReceivablePaise)x.paymentStatus='Partially Received';else if(financial.netReceivablePaise>0&&received>=financial.netReceivablePaise)x.paymentStatus='Received';else if(['Expected','Invoiced','Overdue','Disputed','Written Off'].indexOf(x.paymentStatus)===-1)x.paymentStatus='Expected';return x;}
  create(d,a){revenueProtected_(d,true);var l=LockService.getScriptLock();l.waitLock(30000);try{var n=new Date(),x=this.calc_(Object.assign({},d,{amountReceived:0,outstandingAmount:0,receivedDate:'',reconciliationReference:''}));x.revenueId='REV-'+Utilities.getUuid().slice(0,8).toUpperCase();x.paymentStatus=x.paymentStatus||'Expected';x.createdAt=n;x.createdBy=a||'System';x.updatedAt=n;x.updatedBy=x.createdBy;x.recordVersion=1;x.isDeleted=false;this.valid_(x);this.sheet.appendRow(this.row_(x));return this.find(x.revenueId,true);}finally{l.releaseLock();}}
  find(id,includeDeleted){var matches=this.findAllById(id);if(!matches.length)return null;var value=matches[0];return value.isDeleted&&!includeDeleted?null:value;}
  findAllById(id){if(!id||this.sheet.getLastRow()<2)return[];var target=String(id).toUpperCase();return this.sheet.getRange(2,1,this.sheet.getLastRow()-1,this.h.length).getValues().map(this.obj_.bind(this)).filter(function(row){return String(row.revenueId).toUpperCase()===target;});}
  update(id,d,a,v){revenueProtected_(d,false);var l=LockService.getScriptLock();l.waitLock(30000);try{var r=this.findRow_(id);if(!r)throw new Error('Revenue record not found.');var c=this.obj_(this.sheet.getRange(r,1,1,this.h.length).getValues()[0]);if(v!==undefined&&Number(v)!==c.recordVersion)throw new Error('Revenue version conflict.');var x=this.calc_(Object.assign({},c,d,{updatedAt:new Date(),updatedBy:a||'System',recordVersion:c.recordVersion+1}));this.valid_(x);this.sheet.getRange(r,1,1,this.h.length).setValues([this.row_(x)]);return this.find(id,true);}finally{l.releaseLock();}}
  applyAggregateUnderLock(id,aggregate,actor,now,lock){revenueLockHeld_(lock);var r=this.findRow_(id);if(!r)throw new Error('Revenue record not found.');var c=this.obj_(this.sheet.getRange(r,1,1,this.h.length).getValues()[0]),patch={amountReceived:aggregate.amountReceived,outstandingAmount:aggregate.outstandingAmount,paymentStatus:aggregate.paymentStatus,receivedDate:aggregate.receivedDate,reconciliationReference:aggregate.reconciliationReference,netReceivable:aggregate.netReceivable};if(aggregate.expectedCommission!==undefined&&blankRevenue_(c.expectedCommission))patch.expectedCommission=aggregate.expectedCommission;var changed=Object.keys(patch).some(function(key){return String(c[key]||'')!==String(patch[key]||'');});if(!changed)return c;var x=Object.assign({},c,patch,{updatedAt:now,updatedBy:actor,recordVersion:Number(c.recordVersion||0)+1});this.sheet.getRange(r,1,1,this.h.length).setValues([this.row_(x)]);return x;}
  search(c){c=c||{};var rows=this.sheet.getLastRow()<2?[]:this.sheet.getRange(2,1,this.sheet.getLastRow()-1,this.h.length).getValues(),q=String(c.query||'').toLowerCase(),items=rows.map(this.obj_.bind(this)).filter(function(x){if(x.isDeleted&&!c.includeDeleted)return false;if(c.paymentStatus&&x.paymentStatus!==c.paymentStatus)return false;if(c.companyId&&String(x.companyId).toUpperCase()!==String(c.companyId).toUpperCase())return false;if(c.policyId&&String(x.policyId).toUpperCase()!==String(c.policyId).toUpperCase())return false;return!q||[x.invoiceNumber,x.policyNumber,x.insurerName,x.companyId].some(function(v){return String(v||'').toLowerCase().indexOf(q)!==-1;});});return{items:items,total:items.length};}
  valid_(x){if(!x.policyId)throw new Error('Policy ID is required.');if(!x.insurerName)throw new Error('Insurer Name is required.');if(JSK_REVENUE_SCHEMA.STATUS.indexOf(x.paymentStatus)===-1)throw new Error('Select valid Payment Status.');}
  findRow_(id){if(!id||this.sheet.getLastRow()<2)return 0;var c=this.h.indexOf('Revenue ID')+1,m=this.sheet.getRange(2,c,this.sheet.getLastRow()-1,1).createTextFinder(String(id)).matchEntireCell(true).findNext();return m?m.getRow():0;}
  key_(h){var m={'Revenue ID':'revenueId','Policy ID':'policyId','Company ID':'companyId','GST Amount':'gstAmount','TDS Amount':'tdsAmount'};return m[h]||h.replace(/[^A-Za-z0-9]+(.)/g,function(_,c){return c.toUpperCase();}).replace(/^./,function(c){return c.toLowerCase();});}
  row_(x){var self=this;return this.h.map(function(h){var k=self.key_(h);return x[k]===undefined?'':x[k];});}
  obj_(r){var x={},self=this;this.h.forEach(function(h,i){x[self.key_(h)]=r[i];});x.recordVersion=Number(x.recordVersion||0);x.isDeleted=x.isDeleted===true||String(x.isDeleted).toLowerCase()==='true';return x;}
}
function blankRevenue_(value){return value===null||value===undefined||String(value).trim()==='';}

class RevenuePaymentRepository{
  constructor(options){options=options||{};this.spreadsheet=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet();if(!options.skipMigration&&!options.readOnly)ensureBuild1011Revenue({spreadsheet:this.spreadsheet,actor:options.actor});this.sheet=this.spreadsheet.getSheetByName(JSK_REVENUE_PAYMENT_SCHEMA.SHEET_NAME);if(!this.sheet){if(options.readOnly){this.missing=true;this.h=[];return;}throw new Error('Revenue payment sheet is unavailable.');}this.h=this.sheet.getRange(1,1,1,this.sheet.getLastColumn()).getDisplayValues()[0];var expected=JSK_REVENUE_PAYMENT_SCHEMA.LEGACY_HEADERS.concat(JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS);if(this.h.length!==expected.length||this.h.some(function(v,i){return v!==expected[i];}))throw new Error('Revenue payment sheet schema is unsupported.');}
  key_(h){var m={'Payment ID':'paymentId','Revenue ID':'revenueId','Payment Date':'paymentDate','Request Key':'requestKey','Payload Fingerprint':'payloadFingerprint','Completed At':'completedAt','Completed By':'completedBy','Recovery At':'recoveryAt','Recovery By':'recoveryBy','Last Error':'lastError','Created At':'createdAt','Created By':'createdBy'};return m[h]||h.replace(/[^A-Za-z0-9]+(.)/g,function(_,c){return c.toUpperCase();}).replace(/^./,function(c){return c.toLowerCase();});}
  obj_(row){var value={},self=this;this.h.forEach(function(header,index){value[self.key_(header)]=row[index];});value.legacy=/^RPK-MIG-/.test(String(value.requestKey||''));return value;}
  row_(value){var self=this;return this.h.map(function(header){var key=self.key_(header);return value[key]===undefined?'':value[key];});}
  all(){if(this.missing)return[];return this.sheet.getLastRow()<2?[]:this.sheet.getRange(2,1,this.sheet.getLastRow()-1,this.h.length).getValues().map(this.obj_.bind(this));}
  readWindow(offset,limit){if(this.missing)return{totalLedgerRows:0,rows:[],missing:true};var total=Math.max(0,this.sheet.getLastRow()-1),count=Math.max(0,Math.min(limit,total-offset)),rows=count?this.sheet.getRange(offset+2,1,count,this.h.length).getValues().map(this.obj_.bind(this)):[];return{totalLedgerRows:total,rows:rows,missing:false};}
  appendAcceptedUnderLock(row,lock){revenueLockHeld_(lock);this.sheet.appendRow(this.row_(row));}
  findRow_(id){if(this.sheet.getLastRow()<2)return 0;var cell=this.sheet.getRange(2,1,this.sheet.getLastRow()-1,1).createTextFinder(String(id)).matchEntireCell(true).findNext();return cell?cell.getRow():0;}
  patchUnderLock_(id,patch,lock){revenueLockHeld_(lock);var row=this.findRow_(id);if(!row)throw new Error('Payment row not found.');var current=this.obj_(this.sheet.getRange(row,1,1,this.h.length).getValues()[0]);Object.keys(patch).forEach(function(key){current[key]=patch[key];});this.sheet.getRange(row,1,1,this.h.length).setValues([this.row_(current)]);return current;}
  completeUnderLock(id,actor,now,lock){return this.patchUnderLock_(id,{state:'COMPLETED',completedAt:now,completedBy:actor,lastError:''},lock);}
  recoverUnderLock(id,actor,now,lock){return this.patchUnderLock_(id,{state:'COMPLETED',completedAt:now,completedBy:actor,recoveryAt:now,recoveryBy:actor,lastError:''},lock);}
  backfillUnderLock(id,patch,lock){revenueLockHeld_(lock);var row=this.findRow_(id);if(!row)throw new Error('Payment row not found.');var self=this,values=JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS.map(function(header){var key=self.key_(header);return patch[key]===undefined?'':patch[key];});this.sheet.getRange(row,JSK_REVENUE_PAYMENT_SCHEMA.LEGACY_HEADERS.length+1,1,JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS.length).setValues([values]);return patch;}
}

function revenuePaymentService_(options){options=options||{};var spreadsheet=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet(),paymentRepository=options.paymentRepository||new RevenuePaymentRepository({spreadsheet:spreadsheet,skipMigration:true,readOnly:options.readOnly}),revenueRepository=options.revenueRepository;if(!revenueRepository&&options.readOnly)revenueRepository={findAllById:function(id){return new RevenueRepository({spreadsheet:spreadsheet,skipMigration:true,readOnly:true}).findAllById(id);},applyAggregateUnderLock:function(){throw new Error('Read-only Revenue repository cannot mutate.');}};if(!revenueRepository)revenueRepository=new RevenueRepository({spreadsheet:spreadsheet,skipMigration:true});return JSKOS.RevenuePayment.create({paymentRepository:paymentRepository,revenueRepository:revenueRepository,lockProvider:options.lockProvider||function(){return LockService.getScriptLock();},clock:options.clock||function(){return new Date();},uuid:options.uuid||function(){return Utilities.getUuid();},hash:options.hash||revenueHash_,flush:options.flush||function(){SpreadsheetApp.flush();},day:options.day||revenueDay_,fault:options.fault});}
function revenueApi_(op,fn){try{var context=JSKOS.AccessControl.requireModuleOperation('revenue',op);return{success:true,data:JSON.parse(JSON.stringify(fn(context))),error:null};}catch(e){return{success:false,data:e.data||null,error:{message:e.message||String(e),code:e.code||''}};}}
function apiRevenueCreate(p){p=p||{};return revenueApi_('create',function(context){var actor=revenueServerActor_(context);ensureBuild1011Revenue({actor:actor});return new RevenueRepository({skipMigration:true}).create(p.data||p,actor);});}
function apiRevenueUpdate(p){p=p||{};return revenueApi_('update',function(context){var actor=revenueServerActor_(context);ensureBuild1011Revenue({actor:actor});return new RevenueRepository({skipMigration:true}).update(p.revenueId,p.data||{},actor,p.expectedVersion);});}
function apiRevenueSearch(p){return revenueApi_('search',function(){ensureBuild1011Revenue();return new RevenueRepository({skipMigration:true,readOnly:true}).search(p||{});});}
function getRevenueFilters(){JSKOS.AccessControl.requireModuleOperation('revenue','view');return{statuses:JSK_REVENUE_SCHEMA.STATUS.slice()};}
function apiRevenueSummary(){return revenueApi_('summary',function(){ensureBuild1011Revenue();var a=new RevenueRepository({skipMigration:true,readOnly:true}).search({}).items||[],r={expected:0,received:0,outstanding:0,overdue:0};a.forEach(function(x){r.expected+=Number(x.netReceivable||0);r.received+=Number(x.amountReceived||0);r.outstanding+=Number(x.outstandingAmount||0);if(x.paymentStatus==='Overdue')r.overdue++;});return r;});}
function apiRevenueIntelligence(){return revenueApi_('intelligence',function(){ensureBuild1011Revenue();var items=new RevenueRepository({skipMigration:true,readOnly:true}).search({}).items||[],today=new Date(),r={ageing:{current:0,days30:0,days60:0,days90Plus:0},insurers:{},monthly:{}};today.setHours(0,0,0,0);items.forEach(function(x){var outstanding=Number(x.outstandingAmount||0),due=x.expectedDate?new Date(x.expectedDate):today,days=Math.max(0,Math.floor((today-due)/86400000));if(days===0)r.ageing.current+=outstanding;else if(days<=30)r.ageing.days30+=outstanding;else if(days<=60)r.ageing.days60+=outstanding;else r.ageing.days90Plus+=outstanding;var insurer=x.insurerName||'Unknown';r.insurers[insurer]=(r.insurers[insurer]||0)+outstanding;if(x.receivedDate){var month=String(x.receivedDate).slice(0,7);r.monthly[month]=(r.monthly[month]||0)+Number(x.amountReceived||0);}});return r;});}
function apiRevenueRecordPayment(p){p=p||{};return revenueApi_('record-payment',function(context){var actor=revenueServerActor_(context),request={revenueId:p.revenueId,requestKey:p.requestKey,amount:p.amount,paymentDate:p.paymentDate,reference:p.reference,notes:p.notes};JSKOS.RevenuePayment.request(request);ensureBuild1011Revenue({actor:actor});return revenuePaymentService_().record(request,actor);});}
function apiRevenuePaymentHistory(p){p=p||{};return revenueApi_('history',function(){try{return revenuePaymentService_({readOnly:true}).history({revenueId:p.revenueId,offset:p.offset});}catch(error){if(!error.code)error.code='REVENUE_PAYMENT_INSPECTION_UNAVAILABLE';throw error;}});}
function apiRevenuePaymentInspection(p){p=p||{};return revenueApi_('inspect',function(){try{return revenuePaymentService_({readOnly:true}).inspect({revenueId:p.revenueId,requestKey:p.requestKey,offset:p.offset});}catch(error){if(!error.code)error.code='REVENUE_PAYMENT_INSPECTION_UNAVAILABLE';throw error;}});}
function apiRevenueReconcilePayments(p){p=p||{};return revenueApi_('reconcile',function(context){return revenuePaymentService_({readOnly:false}).reconcile({revenueId:p.revenueId},revenueServerActor_(context));});}
function apiRevenueExport(){return revenueApi_('export',function(){ensureBuild1011Revenue();var items=new RevenueRepository({skipMigration:true,readOnly:true}).search({}).items||[],headers=['Revenue ID','Policy ID','Insurer','Net Receivable','Received','Outstanding','Status','Expected Date'],lines=[headers.join(',')];items.forEach(function(x){lines.push([x.revenueId,x.policyId,x.insurerName,x.netReceivable,x.amountReceived,x.outstandingAmount,x.paymentStatus,x.expectedDate].map(function(v){return'"'+String(v==null?'':v).replace(/"/g,'""')+'"';}).join(','));});return{fileName:'JSK_OS_Revenue_Export.csv',csv:lines.join('\n')};});}
