/** JSK OS Build 1024 - Revenue and durable payment management. */
var JSK_REVENUE_SCHEMA=Object.freeze({VERSION:2,SHEET_NAME:'Revenue',KEY:'JSK_OS_REVENUE_SCHEMA_VERSION',HEADERS:Object.freeze(['Revenue ID','Invoice Number','Policy ID','Company ID','Insurer Name','Policy Number','Business Type','Premium Amount','Commission Rate','Expected Commission','GST Amount','TDS Amount','Net Receivable','Amount Received','Outstanding Amount','Payment Status','Expected Date','Received Date','Reconciliation Reference','Assigned Owner','Notes','Created At','Created By','Updated At','Updated By','Record Version','Is Deleted']),STATUS:Object.freeze(['Expected','Invoiced','Partially Received','Received','Overdue','Disputed','Written Off'])});
var JSK_REVENUE_PAYMENT_SCHEMA=Object.freeze({VERSION:2,SHEET_NAME:'Revenue_Payments',LEGACY_HEADERS:Object.freeze(['Payment ID','Revenue ID','Payment Date','Amount','Reference','Notes','Created At','Created By']),CONTROL_HEADERS:Object.freeze(['Request Key','Payload Fingerprint','State','Completed At','Completed By','Recovery At','Recovery By','Last Error']),KEY:'JSK_OS_REVENUE_PAYMENT_SCHEMA_VERSION'});

function revenueHash_(value){var bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(value),Utilities.Charset.UTF_8);return bytes.map(function(x){return('0'+((x+256)%256).toString(16)).slice(-2);}).join('');}
function revenueDay_(value){return Utilities.formatDate(value instanceof Date?value:new Date(value),JSKOS.Config.APP.TIMEZONE,'yyyy-MM-dd');}
function revenueServerActor_(context){return JSKOS.RevenuePayment.email(context&&context.email);}
function revenueLockHeld_(lock){if(!lock||(typeof lock.hasLock==='function'&&!lock.hasLock()))throw new Error('Authoritative Revenue lock is required.');}
function revenueProtected_(data,creating){var protectedFields=['amountReceived','outstandingAmount','receivedDate','reconciliationReference'];protectedFields.forEach(function(key){if(Object.prototype.hasOwnProperty.call(data||{},key))throw new Error(key+' is ledger-derived and cannot be edited.');});if(Object.prototype.hasOwnProperty.call(data||{},'paymentStatus')&&['Received','Partially Received'].indexOf(String(data.paymentStatus))!==-1)throw new Error('Payment Status is ledger-derived and cannot be edited.');if(creating&&Object.prototype.hasOwnProperty.call(data||{},'recordVersion'))throw new Error('Record Version cannot be supplied.');}

function migrateRevenueDatabase(){return migrateRevenueDatabaseWithOptions_({actor:JSKOS.ConfigService.getCurrentUser()});}
function migrateRevenueDatabaseWithOptions_(options){
  options=options||{};var actor=JSKOS.RevenuePayment.email(options.actor),lock=(options.lockProvider||function(){return LockService.getScriptLock();})(),fault=options.fault||function(){},acquired=false;
  try{try{lock.waitLock(30000);acquired=true;}catch(error){var busy=new Error('Revenue migration is busy.');busy.code='REVENUE_MIGRATION_LOCK_UNAVAILABLE';throw busy;}
    var ss=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet(),props=options.properties||PropertiesService.getScriptProperties(),existingRevenue=ss.getSheetByName(JSK_REVENUE_SCHEMA.SHEET_NAME),existingPayments=ss.getSheetByName(JSK_REVENUE_PAYMENT_SCHEMA.SHEET_NAME),expectedPaymentHeaders=JSK_REVENUE_PAYMENT_SCHEMA.LEGACY_HEADERS.concat(JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS);if(Number(props.getProperty(JSK_REVENUE_SCHEMA.KEY)||0)>=2&&Number(props.getProperty(JSK_REVENUE_PAYMENT_SCHEMA.KEY)||0)>=2&&existingRevenue&&existingPayments){var verifiedRevenueHeaders=existingRevenue.getRange(1,1,1,existingRevenue.getLastColumn()).getDisplayValues()[0],verifiedPaymentHeaders=existingPayments.getRange(1,1,1,existingPayments.getLastColumn()).getDisplayValues()[0],revenueVerified=JSK_REVENUE_SCHEMA.HEADERS.every(function(header){return verifiedRevenueHeaders.indexOf(header)!==-1;}),paymentsVerified=verifiedPaymentHeaders.length===expectedPaymentHeaders.length&&verifiedPaymentHeaders.every(function(header,index){return header===expectedPaymentHeaders[index];});if(revenueVerified&&paymentsVerified)return{success:true,schemaVersion:2,paymentSchemaVersion:2};}
    var revenueSheet=existingRevenue||ss.insertSheet(JSK_REVENUE_SCHEMA.SHEET_NAME),revenueHeaders=revenueSheet.getLastColumn()?revenueSheet.getRange(1,1,1,revenueSheet.getLastColumn()).getDisplayValues()[0]:[];
    if(!revenueHeaders.some(String)){revenueSheet.getRange(1,1,1,JSK_REVENUE_SCHEMA.HEADERS.length).setValues([JSK_REVENUE_SCHEMA.HEADERS.slice()]);revenueHeaders=JSK_REVENUE_SCHEMA.HEADERS.slice();}
    else{if(revenueHeaders.indexOf('Revenue ID')===-1)throw new Error('Revenue sheet schema is unsupported.');JSK_REVENUE_SCHEMA.HEADERS.forEach(function(header){if(revenueHeaders.indexOf(header)===-1){revenueSheet.getRange(1,revenueSheet.getLastColumn()+1).setValue(header);revenueHeaders.push(header);}});}
    var paymentSheet=existingPayments||ss.insertSheet(JSK_REVENUE_PAYMENT_SCHEMA.SHEET_NAME),headers=paymentSheet.getLastColumn()?paymentSheet.getRange(1,1,1,paymentSheet.getLastColumn()).getDisplayValues()[0]:[],legacy=JSK_REVENUE_PAYMENT_SCHEMA.LEGACY_HEADERS.slice(),canonical=legacy.concat(JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS);
    function same(a,b){return a.length===b.length&&a.every(function(value,index){return value===b[index];});}
    var emptyLayout=!headers.some(String),legacyLayout=same(headers,legacy),canonicalLayout=same(headers,canonical);if(!emptyLayout&&!legacyLayout&&!canonicalLayout)throw new Error('Revenue payment sheet schema is unsupported.');
    var revenueRepo=new RevenueRepository({spreadsheet:ss,skipMigration:true}),revenues=revenueRepo.search({includeDeleted:true}).items,byRevenue={};revenues.forEach(function(row){if(byRevenue[String(row.revenueId).toUpperCase()])throw new Error('Duplicate Revenue ID.');byRevenue[String(row.revenueId).toUpperCase()]=row;});
    var rawRows=emptyLayout||paymentSheet.getLastRow()<2?[]:paymentSheet.getRange(2,1,paymentSheet.getLastRow()-1,legacy.length).getValues(),preflightIds={};rawRows.forEach(function(row){var id=String(row[0]||'').trim(),rid=String(row[1]||'').trim().toUpperCase();if(!id||preflightIds[id])throw new Error('Legacy Payment ID is missing or duplicated.');preflightIds[id]=true;if(!byRevenue[rid])throw new Error('Legacy payment has an orphan Revenue ID.');JSKOS.RevenuePayment.paymentPaise(row[3]);JSKOS.RevenuePayment.dateDay(row[2],true);if(/^[=+\-@]/.test(String(row[4]||'').trim())||/^[=+\-@]/.test(String(row[5]||'').trim())||/^[=+\-@]/.test(String(row[7]||'').trim()))throw new Error('Legacy payment contains formula-like text.');var acceptedAt=row[6] instanceof Date?row[6]:new Date(row[6]);if(isNaN(acceptedAt.getTime()))throw new Error('Legacy payment acceptance time is invalid.');});
    if(emptyLayout){paymentSheet.getRange(1,1,1,canonical.length).setValues([canonical]);headers=canonical.slice();fault('afterCanonicalHeaderWrite');}
    else if(legacyLayout){paymentSheet.getRange(1,legacy.length+1,1,JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS.length).setValues([JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS.slice()]);headers=canonical.slice();fault('afterCanonicalHeaderWrite');}
    var paymentRepo=new RevenuePaymentRepository({spreadsheet:ss,skipMigration:true});
    var rows=paymentRepo.all(),populatedControls=rows.filter(function(row){return Boolean(String(row.requestKey||'').trim());});if(populatedControls.length)JSKOS.RevenuePayment.validateRows(populatedControls,revenueHash_);var seen={};rows.forEach(function(row,index){var id=String(row.paymentId||'').trim(),rid=String(row.revenueId||'').trim().toUpperCase();if(!id||seen[id])throw new Error('Legacy Payment ID is missing or duplicated.');seen[id]=true;if(!byRevenue[rid])throw new Error('Legacy payment has an orphan Revenue ID.');JSKOS.RevenuePayment.paymentPaise(row.amount);JSKOS.RevenuePayment.dateDay(row.paymentDate,true);if(/^[=+\-@]/.test(String(row.reference||'').trim())||/^[=+\-@]/.test(String(row.notes||'').trim()))throw new Error('Legacy payment contains formula-like text.');if(!row.requestKey){var digest=revenueHash_(JSON.stringify([index+2,row.paymentId,row.revenueId,String(row.paymentDate),row.amount,row.reference,row.notes,String(row.createdAt),row.createdBy])),key='RPK-MIG-'+digest.slice(0,24).toUpperCase(),request={requestKey:key,revenueId:rid,amount:row.amount,paymentDate:revenueDay_(row.paymentDate),reference:row.reference||'',notes:row.notes||''},fingerprint=revenueHash_(['revenueId',rid,'amount',JSKOS.RevenuePayment.paymentPaise(row.amount),'date',request.paymentDate,'reference',request.reference,'notes',request.notes].join('|'));paymentRepo.backfillUnderLock(row.paymentId,{requestKey:key,payloadFingerprint:fingerprint,state:'COMPLETED',completedAt:row.createdAt,completedBy:row.createdBy,recoveryAt:'',recoveryBy:'',lastError:''},lock);fault('afterControlRowBackfill',{paymentId:row.paymentId});}});
    rows=paymentRepo.all();revenues.forEach(function(revenue){if(revenue.isDeleted)return;var target=rows.filter(function(row){return String(row.revenueId).toUpperCase()===String(revenue.revenueId).toUpperCase();}),sum=0;target.forEach(function(row){sum+=JSKOS.RevenuePayment.paymentPaise(row.amount);});var legacyReceived=JSKOS.RevenuePayment.moneyPaise(revenue.amountReceived||0);if(legacyReceived>sum){var difference=legacyReceived-sum,digest=revenueHash_('BASELINE|'+String(revenue.revenueId).toUpperCase()+'|'+difference),paymentId='PAY-MIG-'+digest.slice(0,12).toUpperCase(),requestKey='RPK-MIG-'+digest.slice(0,24).toUpperCase(),existing=rows.filter(function(row){return row.paymentId===paymentId||row.requestKey===requestKey;});if(existing.length){if(existing.length!==1||String(existing[0].revenueId).toUpperCase()!==String(revenue.revenueId).toUpperCase()||JSKOS.RevenuePayment.paymentPaise(existing[0].amount)!==difference)throw new Error('Synthetic migration identity collision.');}else{var dateValue=revenue.receivedDate||revenue.updatedAt||revenue.createdAt;if(!dateValue)throw new Error('Synthetic balance date is unavailable.');var synthetic={paymentId:paymentId,revenueId:revenue.revenueId,paymentDate:revenueDay_(dateValue),amount:difference/100,reference:'Legacy received balance',notes:'',createdAt:new Date(),createdBy:actor,requestKey:requestKey,payloadFingerprint:revenueHash_('BASELINE|'+String(revenue.revenueId).toUpperCase()+'|'+difference),state:'COMPLETED',completedAt:new Date(),completedBy:actor,recoveryAt:'',recoveryBy:'',lastError:''};paymentRepo.appendAcceptedUnderLock(synthetic,lock);rows.push(synthetic);fault('afterSyntheticAppend',{paymentId:paymentId});}}var valid=paymentRepo.all().filter(function(row){return String(row.revenueId).toUpperCase()===String(revenue.revenueId).toUpperCase();}).map(function(row){return Object.assign({},row,{legacy:/^RPK-MIG-/.test(row.requestKey)});}),normalized=JSKOS.RevenuePayment.validateRows(valid,revenueHash_,String(revenue.revenueId).toUpperCase()),aggregate=JSKOS.RevenuePayment.aggregate(normalized,revenue);revenueRepo.applyAggregateUnderLock(revenue.revenueId,aggregate,actor,new Date(),lock);fault('afterAggregateRepair',{revenueId:revenue.revenueId});});
    fault('beforePropertyCommit');props.setProperty(JSK_REVENUE_SCHEMA.KEY,'2');props.setProperty(JSK_REVENUE_PAYMENT_SCHEMA.KEY,'2');return{success:true,schemaVersion:2,paymentSchemaVersion:2};
  }finally{if(acquired)lock.releaseLock();}
}
function ensureBuild1011Revenue(options){options=options||{};var ss=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet(),revenue=ss.getSheetByName(JSK_REVENUE_SCHEMA.SHEET_NAME),payments=ss.getSheetByName(JSK_REVENUE_PAYMENT_SCHEMA.SHEET_NAME),props=options.properties||PropertiesService.getScriptProperties(),version=Number(props.getProperty(JSK_REVENUE_SCHEMA.KEY)||0),paymentVersion=Number(props.getProperty(JSK_REVENUE_PAYMENT_SCHEMA.KEY)||0);return!revenue||!payments||version<2||paymentVersion<2?migrateRevenueDatabaseWithOptions_({spreadsheet:ss,properties:props,actor:options.actor||JSKOS.ConfigService.getCurrentUser(),lockProvider:options.lockProvider,fault:options.fault}):{success:true,schemaVersion:2,paymentSchemaVersion:2};}

class RevenueRepository{
  constructor(options){options=options||{};this.spreadsheet=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet();if(!options.skipMigration&&!options.readOnly)ensureBuild1011Revenue({spreadsheet:this.spreadsheet,actor:options.actor});this.sheet=this.spreadsheet.getSheetByName(JSK_REVENUE_SCHEMA.SHEET_NAME);if(!this.sheet)throw new Error('Revenue sheet is unavailable.');this.h=this.sheet.getRange(1,1,1,this.sheet.getLastColumn()).getDisplayValues()[0];}
  calc_(x){var financial=JSKOS.RevenuePayment.financial(x),received=JSKOS.RevenuePayment.moneyPaise(x.amountReceived||0);if(financial.derivedExpected)x.expectedCommission=financial.expectedCommission;x.netReceivable=financial.netReceivable;x.amountReceived=received/100;x.outstandingAmount=Math.max(0,financial.netReceivablePaise-received)/100;if(received>0&&received<financial.netReceivablePaise)x.paymentStatus='Partially Received';else if(financial.netReceivablePaise>0&&received>=financial.netReceivablePaise)x.paymentStatus='Received';else if(['Expected','Invoiced','Overdue','Disputed','Written Off'].indexOf(x.paymentStatus)===-1)x.paymentStatus='Expected';return x;}
  create(d,a){revenueProtected_(d,true);var l=LockService.getScriptLock();l.waitLock(30000);try{var n=new Date(),x=this.calc_(Object.assign({},d,{amountReceived:0,outstandingAmount:0,receivedDate:'',reconciliationReference:''}));x.revenueId='REV-'+Utilities.getUuid().slice(0,8).toUpperCase();x.paymentStatus=x.paymentStatus||'Expected';x.createdAt=n;x.createdBy=a||'System';x.updatedAt=n;x.updatedBy=x.createdBy;x.recordVersion=1;x.isDeleted=false;this.valid_(x);this.sheet.appendRow(this.row_(x));return this.find(x.revenueId,true);}finally{l.releaseLock();}}
  find(id,includeDeleted){var matches=this.findAllById(id);if(!matches.length)return null;var value=matches[0];return value.isDeleted&&!includeDeleted?null:value;}
  findAllById(id){if(!id||this.sheet.getLastRow()<2)return[];var target=String(id).toUpperCase();return this.sheet.getRange(2,1,this.sheet.getLastRow()-1,this.h.length).getValues().map(this.obj_.bind(this)).filter(function(row){return String(row.revenueId).toUpperCase()===target;});}
  update(id,d,a,v){revenueProtected_(d,false);var l=LockService.getScriptLock();l.waitLock(30000);try{var r=this.findRow_(id);if(!r)throw new Error('Revenue record not found.');var c=this.obj_(this.sheet.getRange(r,1,1,this.h.length).getValues()[0]);if(v!==undefined&&Number(v)!==c.recordVersion)throw new Error('Revenue version conflict.');var x=this.calc_(Object.assign({},c,d,{updatedAt:new Date(),updatedBy:a||'System',recordVersion:c.recordVersion+1}));this.valid_(x);this.sheet.getRange(r,1,1,this.h.length).setValues([this.row_(x)]);return this.find(id,true);}finally{l.releaseLock();}}
  applyAggregateUnderLock(id,aggregate,actor,now,lock){revenueLockHeld_(lock);var r=this.findRow_(id);if(!r)throw new Error('Revenue record not found.');var c=this.obj_(this.sheet.getRange(r,1,1,this.h.length).getValues()[0]),patch={amountReceived:aggregate.amountReceived,outstandingAmount:aggregate.outstandingAmount,paymentStatus:aggregate.paymentStatus,receivedDate:aggregate.receivedDate,reconciliationReference:aggregate.reconciliationReference,netReceivable:aggregate.netReceivable};if(aggregate.expectedCommission!==undefined&&blankRevenue_(c.expectedCommission))patch.expectedCommission=aggregate.expectedCommission;var changed=Object.keys(patch).some(function(key){return String(c[key]||'')!==String(patch[key]||'');});if(!changed)return c;var x=Object.assign({},c,patch,{updatedAt:now,updatedBy:actor,recordVersion:Number(c.recordVersion||0)+1});this.sheet.getRange(r,1,1,this.h.length).setValues([this.row_(x)]);return x;}
  search(c){c=c||{};var rows=this.sheet.getLastRow()<2?[]:this.sheet.getRange(2,1,this.sheet.getLastRow()-1,this.h.length).getValues(),q=String(c.query||'').toLowerCase(),items=rows.map(this.obj_.bind(this)).filter(function(x){if(x.isDeleted&&!c.includeDeleted)return false;if(c.paymentStatus&&x.paymentStatus!==c.paymentStatus)return false;if(c.companyId&&String(x.companyId).toUpperCase()!==String(c.companyId).toUpperCase())return false;if(c.policyId&&String(x.policyId).toUpperCase()!==String(c.policyId).toUpperCase())return false;return!q||[x.invoiceNumber,x.policyNumber,x.insurerName,x.companyId].some(function(v){return String(v||'').toLowerCase().indexOf(q)!==-1;});});return{items:items,total:items.length};}
  valid_(x){if(!x.policyId)throw new Error('Policy ID is required.');if(!x.insurerName)throw new Error('Insurer Name is required.');if(JSK_REVENUE_SCHEMA.STATUS.indexOf(x.paymentStatus)===-1)throw new Error('Select valid Payment Status.');}
  findRow_(id){if(!id||this.sheet.getLastRow()<2)return 0;var c=this.h.indexOf('Revenue ID')+1,m=this.sheet.getRange(2,c,this.sheet.getLastRow()-1,1).createTextFinder(String(id)).matchEntireCell(true).findNext();return m?m.getRow():0;}
  key_(h){var m={'Revenue ID':'revenueId','Policy ID':'policyId','Company ID':'companyId','GST Amount':'gstAmount','TDS Amount':'tdsAmount'};return m[h]||h.replace(/[^A-Za-z0-9]+(.)/g,function(_,c){return c.toUpperCase();}).replace(/^./,function(c){return c.toLowerCase();});}
  row_(x){var self=this;return this.h.map(function(h){var k=self.key_(h);return x[k]===undefined?'':x[k];});}
  obj_(r){var x={},self=this;this.h.forEach(function(h,i){x[self.key_(h)]=r[i];});x.recordVersion=Number(x.recordVersion||0);x.isDeleted=x.isDeleted===true||String(x.isDeleted).toLowerCase()==='true';return x;}
}
function blankRevenue_(value){return value===null||value===undefined||String(value).trim()==='';}

class RevenuePaymentRepository{
  constructor(options){options=options||{};this.spreadsheet=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet();if(!options.skipMigration&&!options.readOnly)ensureBuild1011Revenue({spreadsheet:this.spreadsheet,actor:options.actor});this.sheet=this.spreadsheet.getSheetByName(JSK_REVENUE_PAYMENT_SCHEMA.SHEET_NAME);if(!this.sheet){if(options.readOnly){this.missing=true;this.h=[];return;}throw new Error('Revenue payment sheet is unavailable.');}this.h=this.sheet.getRange(1,1,1,this.sheet.getLastColumn()).getDisplayValues()[0];var expected=JSK_REVENUE_PAYMENT_SCHEMA.LEGACY_HEADERS.concat(JSK_REVENUE_PAYMENT_SCHEMA.CONTROL_HEADERS);if(this.h.length!==expected.length||this.h.some(function(v,i){return v!==expected[i];}))throw new Error('Revenue payment sheet schema is unsupported.');}
  key_(h){var m={'Payment ID':'paymentId','Revenue ID':'revenueId','Payment Date':'paymentDate','Request Key':'requestKey','Payload Fingerprint':'payloadFingerprint','Completed At':'completedAt','Completed By':'completedBy','Recovery At':'recoveryAt','Recovery By':'recoveryBy','Last Error':'lastError','Created At':'createdAt','Created By':'createdBy'};return m[h]||h.replace(/[^A-Za-z0-9]+(.)/g,function(_,c){return c.toUpperCase();}).replace(/^./,function(c){return c.toLowerCase();});}
  obj_(row){var value={},self=this;this.h.forEach(function(header,index){value[self.key_(header)]=row[index];});value.legacy=/^RPK-MIG-/.test(String(value.requestKey||''));return value;}
  row_(value){var self=this;return this.h.map(function(header){var key=self.key_(header);return value[key]===undefined?'':value[key];});}
  all(){if(this.missing)return[];return this.sheet.getLastRow()<2?[]:this.sheet.getRange(2,1,this.sheet.getLastRow()-1,this.h.length).getValues().map(this.obj_.bind(this));}
  readWindow(offset,limit){if(this.missing)return{totalLedgerRows:0,rows:[],missing:true};var total=Math.max(0,this.sheet.getLastRow()-1),count=Math.max(0,Math.min(limit,total-offset)),rows=count?this.sheet.getRange(offset+2,1,count,this.h.length).getValues().map(this.obj_.bind(this)):[];return{totalLedgerRows:total,rows:rows,missing:false};}
  appendAcceptedUnderLock(row,lock){revenueLockHeld_(lock);this.sheet.appendRow(this.row_(row));}
  findRow_(id){if(this.sheet.getLastRow()<2)return 0;var cell=this.sheet.getRange(2,1,this.sheet.getLastRow()-1,1).createTextFinder(String(id)).matchEntireCell(true).findNext();return cell?cell.getRow():0;}
  patchUnderLock_(id,patch,lock){revenueLockHeld_(lock);var row=this.findRow_(id);if(!row)throw new Error('Payment row not found.');var current=this.obj_(this.sheet.getRange(row,1,1,this.h.length).getValues()[0]);Object.keys(patch).forEach(function(key){current[key]=patch[key];});this.sheet.getRange(row,1,1,this.h.length).setValues([this.row_(current)]);return current;}
  completeUnderLock(id,actor,now,lock){return this.patchUnderLock_(id,{state:'COMPLETED',completedAt:now,completedBy:actor,lastError:''},lock);}
  recoverUnderLock(id,actor,now,lock){return this.patchUnderLock_(id,{state:'COMPLETED',completedAt:now,completedBy:actor,recoveryAt:now,recoveryBy:actor,lastError:''},lock);}
  backfillUnderLock(id,patch,lock){return this.patchUnderLock_(id,patch,lock);}
}

function revenuePaymentService_(options){options=options||{};var spreadsheet=options.spreadsheet||JSKOS.ConfigService.getSpreadsheet(),paymentRepository=options.paymentRepository||new RevenuePaymentRepository({spreadsheet:spreadsheet,skipMigration:true,readOnly:options.readOnly}),revenueRepository=options.revenueRepository;if(!revenueRepository&&options.readOnly)revenueRepository={findAllById:function(id){return new RevenueRepository({spreadsheet:spreadsheet,skipMigration:true,readOnly:true}).findAllById(id);},applyAggregateUnderLock:function(){throw new Error('Read-only Revenue repository cannot mutate.');}};if(!revenueRepository)revenueRepository=new RevenueRepository({spreadsheet:spreadsheet,skipMigration:true});return JSKOS.RevenuePayment.create({paymentRepository:paymentRepository,revenueRepository:revenueRepository,lockProvider:options.lockProvider||function(){return LockService.getScriptLock();},clock:options.clock||function(){return new Date();},uuid:options.uuid||function(){return Utilities.getUuid();},hash:options.hash||revenueHash_,flush:options.flush||function(){SpreadsheetApp.flush();},day:options.day||revenueDay_,fault:options.fault});}
function revenueApi_(op,fn){try{var context=JSKOS.AccessControl.requireModuleOperation('revenue',op);return{success:true,data:JSON.parse(JSON.stringify(fn(context))),error:null};}catch(e){return{success:false,data:e.data||null,error:{message:e.message||String(e),code:e.code||''}};}}
function apiRevenueCreate(p){p=p||{};return revenueApi_('create',function(context){var actor=revenueServerActor_(context);ensureBuild1011Revenue({actor:actor});return new RevenueRepository({skipMigration:true}).create(p.data||p,actor);});}
function apiRevenueUpdate(p){p=p||{};return revenueApi_('update',function(context){var actor=revenueServerActor_(context);ensureBuild1011Revenue({actor:actor});return new RevenueRepository({skipMigration:true}).update(p.revenueId,p.data||{},actor,p.expectedVersion);});}
function apiRevenueSearch(p){return revenueApi_('search',function(context){ensureBuild1011Revenue({actor:revenueServerActor_(context)});return new RevenueRepository({skipMigration:true}).search(p||{});});}
function getRevenueFilters(){JSKOS.AccessControl.requireModuleOperation('revenue','view');return{statuses:JSK_REVENUE_SCHEMA.STATUS.slice()};}
function apiRevenueSummary(){return revenueApi_('summary',function(context){ensureBuild1011Revenue({actor:revenueServerActor_(context)});var a=new RevenueRepository({skipMigration:true}).search({}).items||[],r={expected:0,received:0,outstanding:0,overdue:0};a.forEach(function(x){r.expected+=Number(x.netReceivable||0);r.received+=Number(x.amountReceived||0);r.outstanding+=Number(x.outstandingAmount||0);if(x.paymentStatus==='Overdue')r.overdue++;});return r;});}
function apiRevenueIntelligence(){return revenueApi_('intelligence',function(context){ensureBuild1011Revenue({actor:revenueServerActor_(context)});var items=new RevenueRepository({skipMigration:true}).search({}).items||[],today=new Date(),r={ageing:{current:0,days30:0,days60:0,days90Plus:0},insurers:{},monthly:{}};today.setHours(0,0,0,0);items.forEach(function(x){var outstanding=Number(x.outstandingAmount||0),due=x.expectedDate?new Date(x.expectedDate):today,days=Math.max(0,Math.floor((today-due)/86400000));if(days===0)r.ageing.current+=outstanding;else if(days<=30)r.ageing.days30+=outstanding;else if(days<=60)r.ageing.days60+=outstanding;else r.ageing.days90Plus+=outstanding;var insurer=x.insurerName||'Unknown';r.insurers[insurer]=(r.insurers[insurer]||0)+outstanding;if(x.receivedDate){var month=String(x.receivedDate).slice(0,7);r.monthly[month]=(r.monthly[month]||0)+Number(x.amountReceived||0);}});return r;});}
function apiRevenueRecordPayment(p){p=p||{};return revenueApi_('record-payment',function(context){var actor=revenueServerActor_(context),request={revenueId:p.revenueId,requestKey:p.requestKey,amount:p.amount,paymentDate:p.paymentDate,reference:p.reference,notes:p.notes};JSKOS.RevenuePayment.request(request);ensureBuild1011Revenue({actor:actor});return revenuePaymentService_().record(request,actor);});}
function apiRevenuePaymentHistory(p){p=p||{};return revenueApi_('history',function(){try{return revenuePaymentService_({readOnly:true}).history({revenueId:p.revenueId,offset:p.offset});}catch(error){if(!error.code)error.code='REVENUE_PAYMENT_INSPECTION_UNAVAILABLE';throw error;}});}
function apiRevenuePaymentInspection(p){p=p||{};return revenueApi_('inspect',function(){try{return revenuePaymentService_({readOnly:true}).inspect({revenueId:p.revenueId,requestKey:p.requestKey,offset:p.offset});}catch(error){if(!error.code)error.code='REVENUE_PAYMENT_INSPECTION_UNAVAILABLE';throw error;}});}
function apiRevenueReconcilePayments(p){p=p||{};return revenueApi_('reconcile',function(context){return revenuePaymentService_({readOnly:false}).reconcile({revenueId:p.revenueId},revenueServerActor_(context));});}
function apiRevenueExport(){return revenueApi_('export',function(context){ensureBuild1011Revenue({actor:revenueServerActor_(context)});var items=new RevenueRepository({skipMigration:true}).search({}).items||[],headers=['Revenue ID','Policy ID','Insurer','Net Receivable','Received','Outstanding','Status','Expected Date'],lines=[headers.join(',')];items.forEach(function(x){lines.push([x.revenueId,x.policyId,x.insurerName,x.netReceivable,x.amountReceived,x.outstandingAmount,x.paymentStatus,x.expectedDate].map(function(v){return'"'+String(v==null?'':v).replace(/"/g,'""')+'"';}).join(','));});return{fileName:'JSK_OS_Revenue_Export.csv',csv:lines.join('\n')};});}
