/** JSK OS Build 1009 - Endorsement repository. */
class EndorsementRepository {
  constructor() { ensureBuild1009Endorsements(); this.sheet=JSKOS.ConfigService.getSpreadsheet().getSheetByName(JSK_ENDORSEMENT_SCHEMA.SHEET_NAME); this.headers=this.sheet.getRange(1,1,1,this.sheet.getLastColumn()).getDisplayValues()[0]; }
  create(data,actor) { var lock=LockService.getScriptLock(); lock.waitLock(30000); try { var now=new Date(),x=this.normalize_(data||{}); x.endorsementId='END-'+Utilities.getUuid().slice(0,8).toUpperCase(); x.requestNumber=x.requestNumber||x.endorsementId; x.status=x.status||'Draft'; x.priority=x.priority||'Medium'; x.requestDate=x.requestDate||now; x.slaDueDate=x.slaDueDate||new Date(now.getTime()+7*86400000); x.createdAt=now; x.createdBy=actor||Session.getActiveUser().getEmail()||'System'; x.updatedAt=now; x.updatedBy=x.createdBy; x.recordVersion=1; x.isDeleted=false; this.validate_(x); this.sheet.appendRow(this.toRow_(x)); SpreadsheetApp.flush(); return this.findById(x.endorsementId,true); } finally { lock.releaseLock(); } }
  findById(id,includeDeleted) { var row=this.findRow_(id); if(!row)return null; var x=this.fromRow_(this.sheet.getRange(row,1,1,this.headers.length).getValues()[0]); return x.isDeleted&&!includeDeleted?null:x; }
  update(id,changes,actor,expectedVersion) { var lock=LockService.getScriptLock(); lock.waitLock(30000); try { var row=this.findRow_(id); if(!row)throw new Error('Endorsement not found.'); var current=this.fromRow_(this.sheet.getRange(row,1,1,this.headers.length).getValues()[0]); if(current.isDeleted)throw new Error('Endorsement is archived.'); if(expectedVersion!==undefined&&Number(expectedVersion)!==current.recordVersion){var e=new Error('Endorsement was modified by another user.');e.code='VERSION_CONFLICT';e.currentVersion=current.recordVersion;throw e;} var patch=this.normalize_(changes||{}); delete patch.endorsementId; delete patch.isDeleted; if(patch.status&&patch.status!==current.status){this.validateTransition_(current.status,patch.status);if(patch.status==='Submitted'&&!current.submittedAt)patch.submittedAt=new Date();if(patch.status==='Completed'&&!current.completedAt)patch.completedAt=new Date();} var x=Object.assign({},current,patch,{updatedAt:new Date(),updatedBy:actor||'System',recordVersion:current.recordVersion+1}); this.validate_(x); this.sheet.getRange(row,1,1,this.headers.length).setValues([this.toRow_(x)]); SpreadsheetApp.flush(); return this.findById(id,true); } finally { lock.releaseLock(); } }
  remove(id,actor,version) { return this.setArchivedState_(id,true,actor,version); }
  restore(id,actor,version) { return this.setArchivedState_(id,false,actor,version); }
  setArchivedState_(id,archived,actor,version) { var lock=LockService.getScriptLock(); lock.waitLock(30000); try { var row=this.findRow_(id); if(!row)throw new Error('Endorsement not found.'); var x=this.fromRow_(this.sheet.getRange(row,1,1,this.headers.length).getValues()[0]); if(version!==undefined&&Number(version)!==x.recordVersion){var e=new Error('Endorsement was modified by another user.');e.code='VERSION_CONFLICT';e.currentVersion=x.recordVersion;throw e;} if(x.isDeleted===archived)return x; x.isDeleted=archived;x.updatedAt=new Date();x.updatedBy=actor||'System';x.recordVersion+=1; this.sheet.getRange(row,1,1,this.headers.length).setValues([this.toRow_(x)]); SpreadsheetApp.flush(); return this.findById(id,true); } finally { lock.releaseLock(); } }
  search(c) { c=c||{}; var context=JSKOS.ClientContext.normalize({companyId:c.companyId,personId:c.personId,policyIds:c.policyIds||c.policyId},{policyLimit:c.policyLimit}),rows=this.sheet.getLastRow()<2?[]:this.sheet.getRange(2,1,this.sheet.getLastRow()-1,this.headers.length).getValues(),q=String(c.query||'').toLowerCase(); var items=rows.map(this.fromRow_.bind(this)).filter(function(x){if(!c.includeDeleted&&x.isDeleted)return false;if(c.status&&x.status!==c.status)return false;if(c.endorsementType&&x.endorsementType!==c.endorsementType)return false;if(context.active&&!JSKOS.ClientContext.matches(x,context))return false;return !q||[x.requestNumber,x.description,x.insurerReference,x.notes].some(function(v){return String(v||'').toLowerCase().indexOf(q)!==-1;});}); items.sort(function(a,b){return new Date(b.updatedAt||0)-new Date(a.updatedAt||0);}); var limit=Math.max(1,Math.min(Number(c.limit)||250,500)),available=items.length;return {items:items.slice(0,limit),total:available,context:context,meta:{returned:Math.min(available,limit),available:available,truncated:available>limit,limit:limit,queryCount:1}}; }
  validateTransition_(from,to) { if(to==='Cancelled')return; var allowed={'Draft':['Documents Pending','Ready to Submit'],'Documents Pending':['Ready to Submit','Draft'],'Ready to Submit':['Submitted','Documents Pending'],'Submitted':['Insurer Query','Approved','Rejected'],'Insurer Query':['Submitted','Documents Pending'],'Approved':['Completed'],'Rejected':['Draft'],'Completed':[]}; if((allowed[from]||[]).indexOf(to)===-1)throw new Error('Invalid status transition: '+from+' to '+to+'.'); }
  validate_(x) { if(!x.policyId)throw new Error('Policy ID is required.'); if(JSK_ENDORSEMENT_SCHEMA.TYPE_VALUES.indexOf(x.endorsementType)===-1)throw new Error('Select a valid Endorsement Type.'); if(JSK_ENDORSEMENT_SCHEMA.STATUS_VALUES.indexOf(x.status)===-1)throw new Error('Select a valid Status.'); if(JSK_ENDORSEMENT_SCHEMA.PRIORITY_VALUES.indexOf(x.priority)===-1)throw new Error('Select a valid Priority.'); if(Number(x.premiumImpact||0)<0||Number(x.refundImpact||0)<0)throw new Error('Premium and refund impact cannot be negative.'); }
  normalize_(d) { var r={}; Object.keys(d).forEach(function(k){r[k]=d[k];}); ['premiumImpact','refundImpact'].forEach(function(k){if(r[k]!==undefined)r[k]=r[k]===''?'':Number(r[k]);}); return r; }
  findRow_(id) { if(!String(id||'').trim()||this.sheet.getLastRow()<2)return 0; var col=this.headers.indexOf('Endorsement ID')+1,m=this.sheet.getRange(2,col,this.sheet.getLastRow()-1,1).createTextFinder(String(id)).matchEntireCell(true).findNext(); return m?m.getRow():0; }
  toRow_(x) { var self=this; return this.headers.map(function(h){var k=self.key_(h);return x[k]===undefined?'':x[k];}); }
  fromRow_(row) { var x={},self=this; this.headers.forEach(function(h,i){x[self.key_(h)]=row[i];}); x.recordVersion=Number(x.recordVersion||0); x.isDeleted=x.isDeleted===true||String(x.isDeleted).toLowerCase()==='true'; return x; }
  key_(h) { var special={'Endorsement ID':'endorsementId','Company ID':'companyId','Person ID':'personId','Policy ID':'policyId','Document ID':'documentId','Task ID':'taskId','SLA Due Date':'slaDueDate'}; return special[h]||h.replace(/[^A-Za-z0-9]+(.)/g,function(_,c){return c.toUpperCase();}).replace(/^./,function(c){return c.toLowerCase();}); }
}
