/** JSK OS Build 1009 Phase 2 - Endorsement SLA and follow-up automation. */
var JSKOS=JSKOS||{};
JSKOS.EndorsementAutomation=(function(){
  function dateKey_(v){if(!v)return'';var d=v instanceof Date?v:new Date(v);return isNaN(d.getTime())?'':Utilities.formatDate(d,'Asia/Kolkata','yyyy-MM-dd');}
  function runDaily(referenceDate,authority){JSKOS.LegacyMutationAuthority.assertMutation(authority);requireBuild1009Endorsements_();requireBuild1004Tasks_();var actor=JSKOS.LegacyMutationAuthority.actor(authority),repo=new EndorsementRepository(),taskRepo=new TaskRepository(),items=repo.search({}).items||[],tasks=taskRepo.search({}).items||[],today=dateKey_(referenceDate||new Date()),markers={};tasks.forEach(function(t){var m=String(t.description||'').match(/\[AUTO-ENDORSEMENT:([^\]]+)\]/);if(m)markers[m[1]]=true;});var overdue=[],created=0;items.forEach(function(x){if(['Completed','Rejected','Cancelled'].indexOf(x.status)!==-1)return;var due=dateKey_(x.nextActionDate||x.slaDueDate);if(!due||due>=today)return;overdue.push(x);if(markers[x.endorsementId])return;taskRepo.create({title:'Endorsement follow-up '+x.requestNumber,description:'[AUTO-ENDORSEMENT:'+x.endorsementId+'] Overdue endorsement action.',taskType:'Follow-up',status:'Open',priority:x.priority==='Critical'?'Critical':'High',owner:x.assignedOwner||'',dueDate:today,companyId:x.companyId||'',personId:x.personId||'',policyId:x.policyId},actor);created+=1;});var props=PropertiesService.getScriptProperties(),to=String(props.getProperty('JSK_OS_ENDORSEMENT_RECIPIENTS')||props.getProperty('JSK_OS_RENEWAL_DASHBOARD_RECIPIENTS')||'').trim(),sent=false;if(to&&overdue.length){var lines=['JSK OS Endorsement SLA Digest','','Overdue: '+overdue.length,''];overdue.slice(0,25).forEach(function(x){lines.push('- '+x.requestNumber+' | '+x.status+' | '+(x.assignedOwner||'Unassigned'));});MailApp.sendEmail(to,'JSK OS Endorsement SLA Digest',lines.join('\n'));sent=true;}return{overdue:overdue.length,tasksCreated:created,emailSent:sent};}
  return{runDaily:runDaily};
})();
function runDailyEndorsementAutomation(){var authority=JSKOS.LegacyMutationAuthority.requireAdmin('endorsements.automation');return JSKOS.EndorsementAutomation.runDaily(new Date(),authority);}
function runDailyEndorsementAutomation_(){return legacyRunTrustedSystem_('ENDORSEMENT_AUTOMATION',function(authority){return JSKOS.EndorsementAutomation.runDaily(new Date(),authority);});}
function installEndorsementAutomationTrigger(){JSKOS.LegacyMutationAuthority.requireAdmin('endorsements.install-trigger');var h='runDailyEndorsementAutomation_',legacy='runDailyEndorsementAutomation',retained=null,removed=[];ScriptApp.getProjectTriggers().forEach(function(t){var name=t.getHandlerFunction();if(name===legacy||(name===h&&retained)){ScriptApp.deleteTrigger(t);removed.push(name);}else if(name===h)retained=t;});var trigger=retained||ScriptApp.newTrigger(h).timeBased().everyDays(1).atHour(9).create();return{success:true,triggerId:trigger.getUniqueId(),created:!retained,removedHandlers:removed};}
