/** JSK OS Build 1009 - Endorsement public API. */
function endorsementApi_(op,fn){try{return{success:true,data:JSON.parse(JSON.stringify(fn())),error:null,meta:{operation:op}};}catch(e){return{success:false,data:null,error:{message:e.message||String(e),code:e.code||'',details:e.currentVersion?{currentVersion:e.currentVersion}:{}}};}}
function endorsementRepo_(){return new EndorsementRepository();}
function apiEndorsementCreate(p){p=p||{};return endorsementApi_('create',function(){return endorsementRepo_().create(p.data||p,p.actor);});}
function apiEndorsementUpdate(p){p=p||{};return endorsementApi_('update',function(){return endorsementRepo_().update(p.endorsementId,p.data||{},p.actor,p.expectedVersion);});}
function apiEndorsementDelete(p){p=p||{};return endorsementApi_('delete',function(){return endorsementRepo_().remove(p.endorsementId,p.actor,p.expectedVersion);});}
function apiEndorsementRestore(p){p=p||{};return endorsementApi_('restore',function(){return endorsementRepo_().restore(p.endorsementId,p.actor,p.expectedVersion);});}
function apiEndorsementSearch(p){return endorsementApi_('search',function(){return endorsementRepo_().search(p||{});});}
function apiEndorsementSummary(){return endorsementApi_('summary',function(){var items=endorsementRepo_().search({}).items||[],today=new Date();today.setHours(0,0,0,0);var summary={totalOpen:0,overdue:0,pendingDocuments:0,premiumImpact:0,refundImpact:0,averageAgeDays:0,ownerWorkload:[]},owners={},ageTotal=0;items.forEach(function(x){if(['Completed','Rejected','Cancelled'].indexOf(x.status)===-1){summary.totalOpen+=1;var due=x.nextActionDate||x.slaDueDate;if(due&&new Date(due)<today)summary.overdue+=1;if(x.status==='Documents Pending'||String(x.pendingDocuments||'').trim())summary.pendingDocuments+=1;var owner=String(x.assignedOwner||'Unassigned');owners[owner]=(owners[owner]||0)+1;var start=new Date(x.requestDate||x.createdAt);if(!isNaN(start.getTime()))ageTotal+=Math.max(0,Math.floor((today-start)/86400000));}summary.premiumImpact+=Number(x.premiumImpact||0);summary.refundImpact+=Number(x.refundImpact||0);});summary.averageAgeDays=summary.totalOpen?Math.round(ageTotal/summary.totalOpen):0;summary.ownerWorkload=Object.keys(owners).map(function(owner){return{owner:owner,count:owners[owner]};}).sort(function(a,b){return b.count-a.count;});return summary;});}
function getEndorsementFilters(){return{types:JSK_ENDORSEMENT_SCHEMA.TYPE_VALUES.slice(),statuses:JSK_ENDORSEMENT_SCHEMA.STATUS_VALUES.slice(),priorities:JSK_ENDORSEMENT_SCHEMA.PRIORITY_VALUES.slice()};}
